### ISSUE TITLE
Notification with same id isn't being replaced

### ISSUE THREAD

**Issue by kriskast** [katzer/cordova-plugin-local-notifications#1032]
I am scheduling a notification every minute with the same id, instead of replacing the old one, it adds a new one. Is there a way to have it replaced?

**Comment by cokron** [comment]
I am having a similar issue:
I am creating a local notification that is to be fired at 6pm every day.
I use to save the same notification again - with the same ID - when the user makes changes to his settings.
When I ask the OS for the stored notifications, I see just one.

However, many users complain that the keep getting multiple notifications at 6pm instead of just one.

Is this a bug of iOS?
Is there a known workaround?

Any help greatly appreciated, as my customer is getting very upset :-)

**Comment by rwillett** [comment]
You have to delete the old one if you want to assign the same id. Not difficult and gets round the problem that way.

**Comment by rwillett** [comment]
Closed as no update from original poster.
