### ISSUE TITLE
Scheduling notification for PST while in PDT?

### ISSUE THREAD

**Issue by mkn20** [katzer/cordova-plugin-local-notifications#1098]
I need to schedule a notification when the daylight saving time ends and timezone switches to PST from PDT. So, _while a device is still in PDT,_ how to schedule a notification for a date and time **when timezone switches to PST**? The idea is to have notification fired in future still at the correct time when the device timezone changes from PDT to PST? Should scheduling time be adjusted in advance when scheduling? For instance, for a fire date and time of 18th November 8 AM (when PST will be in effect), when scheduling notification while still in PDT, should it be scheduled for 18th November 7 AM or still for 18th November 8 AM? Hope it makes sense! Thanks in advance.

**Comment by mkn20** [comment]
Any and all advice appreciated!

**Comment by Tawpie** [comment]
@mkn20 You don’t need to make adjustments for daylight savings/standard time when you are scheduling, simply schedule as if the phone will take care of all the adjustments (because it does, including when the user travels across timezones). If you want it to fire at 7AM on Nov 8, set it for 7AM on Nov 8.

**Comment by rwillett** [comment]
Can this be closed now?

**Comment by SatguruSharanamMam** [comment]
Yes. Thanks!
