### ISSUE TITLE
iOS 10 - Single Local Notification is not firing.

### ISSUE THREAD

**Issue by hardikdevios** [katzer/cordova-plugin-local-notifications#1114]

**Comment by stbcdt** [comment]
+1. Same issue here. 
I did use {every: "year"} as a workaround. It works for my app because all notifications get canceled once the app gets opened and I can live with the fact that if someone does not open the app for a full year, there will be another (pointless) notification. This is however only a temporary fix until single local notifications can properly be scheduled again!

**Comment by hardikdevios** [comment]
Yes i have used the same but its very major issue

**Comment by preethu2325** [comment]
I have the same issue

**Comment by rejhgadellaabsl** [comment]
+1

**Comment by bnova-stefan** [comment]
+1

**Comment by grahamj** [comment]
+1

**Comment by grahamj** [comment]
Fix here Fix here https://github.com/katzer/cordova-plugin-local-notifications/pull/1107

**Comment by mauricioprzv** [comment]
run that cordova plugin add https://github.com/Telerik-Verified-Plugins/LocalNotification
Its here the documentation http://plugins.telerik.com/cordova/plugin/localnotification
THATS WORKS

**Comment by rwillett** [comment]
If this is still a problem, update with the template in #1188.

**Comment by rwillett** [comment]
Closed as no update from original poster.
