### ISSUE TITLE
Not working on IOS 10

### ISSUE THREAD

**Issue by akkineniramana** [katzer/cordova-plugin-local-notifications#1128]
I have upgraded IOS 9 to 10, now suddenly notifications stops coming. What changes should I do to plugin to make it work?

**Comment by synfony** [comment]
I am using this plugin (source="git" spec="https://github.com/katzer/cordova-plugin-local-notifications#ios10") to get notification while the app is in background. 
It seems that notification gets scheduled without any error but nothing shows up on the Notification screens while the app is in the background.

Please suggest possible solution!!

**Comment by xgzl87** [comment]
me too!!

**Comment by shadmehr** [comment]
me too!!

**Comment by samuelt1** [comment]
me too, but that does not mean i will open a new issue, read the issues, look at issue #1110

**Comment by aoathout** [comment]
I'm using this fork and not having any iOS 10 issues

https://github.com/EddyVerbruggen/cordova-plugin-local-notifications

**Comment by Nuajan** [comment]
Can anybody confirm this issue has been fixed? Not for me, at least.

I'm still facing the same with recent ios 10.1.1
Notification is scheduled but events seem not to work properly: scheduled and cancel events seems to work, but trigger and click no way.
Notification comes up to notification center while in background but while foreground just a simple dialog with a close button and the name of the app as title is shown...

Tested with cordova 6.4.0 and IOS 4.3.0 platform.
Opened specific issue #1135 

is it maybe in progress a new version of the plugin based on UserNotifications API instead of UILocalNotification?

**Comment by RpCoding** [comment]
Like @aoathout  mentioned, it works with the fork from https://github.com/EddyVerbruggen/cordova-plugin-local-notifications - basically the fix is just a few lines long, see https://github.com/EddyVerbruggen/cordova-plugin-local-notifications/commit/5dad35f90e4d9bafc5465f085b2be85398638410

**Comment by marcoliceti** [comment]
Try also [this fork from Telerik](http://plugins.telerik.com/cordova/plugin/localnotification). It worked for me.

**Comment by Nuajan** [comment]
Thanks all,
just testing with IOS10 branch which seems to be the best one at this moment.
Working perfectly on a fresh project but having issues with some other used plugin; still do not know what´s the problem exactly...
I´ll keep you all up to date.

Thanks again.

**Comment by MikaelMalcolm** [comment]
Hi everyone,

Do we know when this will be fixed and merged into master as an official release?

**Comment by rwillett** [comment]
The plugin is being rewritten to handle IOS10. No date is available for the release.
