### ISSUE TITLE
Ability to prevent notification by listening to when it's about to trigger?

### ISSUE THREAD

**Issue by SammyIsra** [katzer/cordova-plugin-local-notifications#1152]
Is there a way to listen to an event (like '$cordovaLocalNotification:trigger') that fires before the event triggers, and cancel the notification from happening? 

I need to evaluate if the notification is still valid, and if it is not, I need the ability to cancel it.

**Comment by rwillett** [comment]
You can always query the notifications and the ```at:``` value to see how close you are.

The downside would be when do you do the test. You can't keep querying it every second, great way to drain the battery.

One way would be to set a timeout to trigger just before the schedule but that requires the app to be in the foreground. Could be tricky for background schedules.

Apart from that, I'm not aware of anything, other people may have better ideas. I suspect @katzer has other things on his mind with the IOS10 work.

Rob

**Comment by B00268219** [comment]
+1 i need to intercept the triggered notification. catching "on.trigger" is to late, any timer i add is killed by device at any time. notification occurs but is not what im after. any ideas?

**Comment by gotters** [comment]
Yes my original solution is not working so great either. i calling the .clear() within the trigger event - because at the end of the day the notification was displayed (even though only briefly). I really need to also intercept it. 

In fact I am now running into issues when .clear() is not even working from within the trigger event? 

I still don't have a good solution for this.

**Comment by katzer** [comment]
No, a `beforetrigger` event is not possible - the OS tells the plugin when a notification has been triggered.
