### ISSUE TITLE
Why ios10 branch isn't merged to master?

### ISSUE THREAD

**Issue by echonox** [katzer/cordova-plugin-local-notifications#1155]
@katzer Any reason why ios10 branch isn't yet merged to master?

iOS10 runs on 73.9% of all devices.

**Comment by Leomhl** [comment]
It's really true. I have the same question!

**Comment by rejhgadellaa** [comment]
I remember reading somewhere that there are some compatibility issues with the master/ios10 branch. So the merger is probably not going to happen until that is resolved?

Also: there is no correlation between the % of users on platform version X and a merge of branch Z on git :)

**Comment by stevesum** [comment]
I would appreciate a merge with the master in the near future, because it
makes the life much complicated if you use a build client (e.g. jenkins)
for the automatic build of the different platform.
Now this option is disabled, if we have to checkout different branches for
different platforms. Therefore we used the iOS10 branch everywhere :(

2017-02-28 15:40 GMT+01:00 Roderick Gadellaa <notifications@github.com>:

**Comment by rwillett** [comment]
The plugin is being rewritten to handle IOS10 as Apple changed the underlying framework. I'm not the author so can't say what will be merged or not.
