### ISSUE TITLE
Notification not fired when app in background

### ISSUE THREAD

**Issue by Malagasy** [katzer/cordova-plugin-local-notifications#1165]
Hi,

on IOS, my app does not fire notification when the app is in background.
on Android, everything's ok.
Here's how it works : a function's always called whenever the datas change in DB(using firebase). When it's called it triggers the notification. I've observed that local notification are only scheduled on foreground.

For example:
1/ put app in bg => change datas on db => nothing appears
2/ put app in bg => change datas on db => go back to fg then instantly press home button (actually notification are scheduled with now()+5seconds) => notification appears after 5 seconds

I won't go for push notification as a workaround, is there any way to make it works ?

Additionnals:
I don't know how this plugin works on previous IOS version, i'm also thinking that IOS10 simply "pause" every JS code when the app is put in bg ? So my function is never called even if datas are changed on db ?

Details :  
- ios 10.1.1
- ionic1
- katzer/cordova plugin local notification#ios10 branch

Thx for helping,

**Comment by rwillett** [comment]
Local Notifications do work when the app is in the background on ios 10. Can't comment on ios11 as wasn't aware that was even released as a beta :) Did you mean ios 10?

Strip your code back so that your DB is not involved and then schedule a notification for 60 secs in the future, put the app in the background and it should appear.

I would show your code for the actual scheduling of the notification. I suspect that is where you are going wrong. Forget the DB as thats nothing to do with local notifications, go back to basics.

It does work, there are other issues with the notification plugin but it does work for ios 8,9 and 10 as well as Android 5 and 6.

Rob

**Comment by Malagasy** [comment]
Indeed, i meant IOS 10.1.1

Your case test looks like my 2/ case, first the notification is scheduled on fg then it appears after 60 seconds on bg. I don't know if i'm clear enough ?
But i'll try something, scheduling a notification inside a 60 secs timeout and see what happens...

Here's current code :
`
	$scope.userLiked = $firebaseArray( ref.child('profileLike').child(currentAuth.id ).child('liked') );

	$scope.userLiked.$watch(function(event, key){

		if( event.event == 'child_removed' )
			return;


		var lastNotificationLikeDate = localStorageService.get('lastNotificationLikeDate');


		if( !lastNotificationLikeDate || lastNotificationLikeDate < $scope.userLiked[ event.key ].date )
		{
			localStorageService.set('lastNotificationLikeDate' , (new Date()).valueOf() );

			var t = new Date();
			t.setSeconds( t.getSeconds() + 5 );

			$cordovaLocalNotification.schedule({
				id: 100,
				title: "Helium Notification",
				icon: ionic.Platform.isAndroid() ? 'file://res/icon/android/logo2.png' : '',
				text: $scope.userLiked[ event.key ].pseudo + " a aimé ton profil.",
				at: ionic.Platform.isAndroid() ? null : t,
				data: {
					username: $scope.userLiked[ event.key ].username
				}
			});
		}
	});`

**Comment by rwillett** [comment]
Observations:

1. Is $cordovaLocalNotification set? We directly call cordova.plugins.notification.local.schedule

2. Your code still has too much extra stuff, how do you know 

```
if( !lastNotificationLikeDate || lastNotificationLikeDate < $scope.userLiked[ event.key ].date )
```
is working. Pull it all out or put 

```
if( 1 || !lastNotificationLikeDate || lastNotificationLikeDate < $scope.userLiked[ event.key ].date )
```

to force the conditional.

3. We use a slightly different method of calculating the future time.

```
        var now      = d.getTime();
        reminder0 = new Date(now + 5 * 1000);
```

I can't remember why we did that, but suspect that it was due to ```now``` coming back in milliseconds. I *think* yours might work, but it might be worth checking exactly what the value of ```t``` really, really is is.

4. We create all the objects that we pass into cordova.plugins.notification.local.schedule() in advance and then put a JSON.stringify() around the lot so we can see exactly what is being passed. Also write some debugging code to show the ```at:`` command in the right ISO format. If you look at it as an integer you lose track of how many digits there are. Its very, very easy to pass a millisec value into at: and not a sec value. Also some of the query routines come back in millisecs so its an utter nightmare at times.

5. We also schedule ALL notifications, whether they are single of multiple ones, in an array. We read there were issues with a passing an object so we now pass an array of objects even if there is only one object.

6. You have no callback to $cordovaLocalNotification.schedule() to indicate success. Well worth putting it in.

7. Your code is broadly similar to outs and ours works fine, so yours should. 

Rob

**Comment by Malagasy** [comment]
Ok, 
there's lot of things you said I haven't tried yet.

I come back later with more testing.

Thx

**Comment by Malagasy** [comment]
Ok, 

i tried 1,2 and 5 and nothing worked.

So i've wrote a $timeout( setTimeout like) and put console.log inside. 


When the app is on background, i've observed that after X seconds the callback function of $timeout is never called. But when i go back to foreground the log appears. 

It looks like IOS blocks javascript execution when the app is on background...

**Comment by rwillett** [comment]
setTimeout (or any JavaScript timeouts) do not work on IOS in the background. Never has.

Something else is wrong as local notifications do work on IOS 10.

1. Have you stripped your code to bare basics?

2. What version of the notification code are you using? I have no idea if the ng-cordova version has been updated for ios10.

**Comment by Malagasy** [comment]
I'm using ios10#branch since the main branch didn't work for me.

The plugin works well when simply using schedule() but isn't working inside a callback function.

Btw, it's working on Android, do you have any clue ?

**Comment by rwillett** [comment]
I have tested it in ios 8,9 and 10. Also Android 5 and 6. 

Show me your stripped back code. I don't understand 

```The plugin works well when simply using schedule() but isn't working inside a callback function.```

Rob

**Comment by ip192** [comment]
I use document.addEventListener('pause', () => {}, false) to resolve my problem

**Comment by rwillett** [comment]
Could you expand on what you are doing exactly? I think it would be helpful. I'm unclear what problem you are solving with the code.

**Comment by ip192** [comment]
I use document.addEventListener('pause', () => {}, false) to add a listener, when my app turn to background, the function () => {} will work.

**Comment by rwillett** [comment]
@ip192 I understand that but thats not the problem here. The Original Poster was trying to figure out how to get local notifications working when the app is in the background. Your code will simply fire when the app goes in the background unless I misunderstand what you are saying. 

We use the same code to do things when the user puts the app in the background but I can't see what you are doing that helps the original problem.

**Comment by Malagasy** [comment]
Hi,

@ip192  : i'll try it asap.

@rwillett : First, thank for you patience and time
My current function works like that : 

`functionFromFirebaseAPI(args,'onDataChange' , myFunctionHandler)`

myFunctionHandler should be called every time datas from database related to 'args' change.

on Ios, myFunctionHandler is never called on bg BUT it 's when app on fg.
==> it means that functionFromFirebaseAPI is not working on bg ==> not related to katzer's plugin then 

Btw , im not saying that notification does not work on bg. When they are scheduled on fg, they'll appear on bg at the given time.
I'm saying that i can't schedule them on background in order to make them appear. 

So i'll try ip192's solution hoping that functions inside pause event are always "active".

**Comment by rwillett** [comment]
@Malagasy 

Now I'm confused. I'm ignoring anything to do with Firebase as thats nothing to do with local notifications. What does 

```
I'm saying that i can't schedule them on background in order to make them appear.
```

mean? Are you trying to actually schedule the notification when the app is in the background? You can't do that as your app is probably not running, its suspended. IOS 10 also appears to suspend apps very, very quickly. Sometimes in a matter of seconds whereas IOS 8 and 9 could take up to 15 minutes. 

Rob

**Comment by Malagasy** [comment]
Sorry lol actually i'm pretty sure that i'm correctly using the API since it works on Android (even when app is paused).

That's exactly what i want to do. (i'm doing a "real-time app with instant chat")

> Are you trying to actually schedule the notification when the app is in the background? You can't do that as your app is probably not running, its suspended.

Indeed, i suspect iOS to suspend any javascript execution when app is on background.

**Comment by rwillett** [comment]
IOS 10 suspends your app very, very quickly the moment you move to the background. AFAIK there is no way to keep your IOS app working in the background when using JavaScript. There are ways around this using Swift.

You don't need to 'suspect' IOS will suspend, it absolutely will suspend your app. Once suspended very few functions are allowed to work. There are various hacks to try and get around this, background playing of audio is one hack and is another cast iron guaranteed way to get your app rejected by Apple.

Our architecture for notifications works by having a central server that sends out updates, initially using a silent notification, if the app is in the foreground or very, very recently in the background, then it responds to our server and the app collects data from the server and displays it using local notifications. If there is no response, because the app is in the background and has been suspended the server will then try again and send 'normal' notifications down to the app. These are then displayed in the notification drawer. Since we have no control over when IOS actually suspends the app, it can be 15 mins, or 30 secs, our architecture automatically adapts. It took a lot of work to get this working right.

Android is wholly different and you can do far more things in the background.

**Comment by Malagasy** [comment]
Ok, everything's clear now.

on IOS, the only way to get real time notification is to send the notification from the server.

Thank you :-)

**Comment by rwillett** [comment]
@Malagasy 

To be very clear.

The only way we know to get real time notifications when a JavaScript app is suspended in the background is sending through Apple's Notification Server.

If this is incorrect, we'd love to know how other people are doing this on a JavaScript app.

Rob
