### ISSUE TITLE
Ticket Template: If you ignore this template, we'll ignore your issue

### ISSUE THREAD

**Issue by katzer** [katzer/cordova-plugin-local-notifications#1188]
__WARNING: If you ignore this template, we'll ignore your issue.__
Provide a general summary of the issue.

## Your Environment
- Plugin version:
- Platform:
- OS version:
- Device manufacturer / model:
- Cordova version (`cordova -v`):
- Cordova platform version (`cordova platform ls`):
- Plugin config

## Expected Behavior
_Tell us what should happen_

## Actual Behavior
_Tell us what happens instead_

## Steps to Reproduce
_Reproduce this issue; include code to reproduce, if relevant_

1. ...
2. ...
3. ...
4. ...

## Context
_What were you trying to do?_

## Debug logs
_Include iOS / Android logs_
- ios XCode logs
- Android: $ adb logcat

**Comment by sengmow** [comment]
Plugin version: 0.8.4	
Platform: Android 
OS version: 5.0.2
Device manufacturer / model: Xiaomi Mi 4i

Expected Behavior:
Repeat notifications are daily as well as hourly and we expect the notifications to trigger every hour and day at the preset time.

Actual Behavior:
Last tested about half a year ago. Inconsistent behaviour.
a) The notifications are received if the app is not completely exited. If exited, at times the daily notifications are received for a few days and stopped.
b) The hourly notifications will work for a few hours and stopped. Regardless the app is running or not.

**Comment by rwillett** [comment]
Show your code. 

What does if app not completely exited mean?

**Comment by sengmow** [comment]
Unfortunately, I did not keep the codes. Give me a week or two and I will
recreate and retest. I am still keen to make use of local notifications.

If left in the background inactive for too long with many other apps, I
think that app is in sort of hibernate mode. Apologies for my terminology
that may not be technically correct.

Thanks.

**Comment by noman0911** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'https://github.com/katzer/cordova-plugin-local-notifications.git',
1 verbose cli   '--save' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData https://github.com/katzer/cordova-plugin-local-notifications.git
8 silly fetchOtherPackageData https://github.com/katzer/cordova-plugin-local-notifications.git
9 silly cache add args [ 'https://github.com/katzer/cordova-plugin-local-notifications.git',
9 silly cache add   null ]
10 verbose cache add spec https://github.com/katzer/cordova-plugin-local-notifications.git
11 silly cache add parsed spec Result {
11 silly cache add   raw: 'https://github.com/katzer/cordova-plugin-local-notifications.git',
11 silly cache add   scope: null,
11 silly cache add   escapedName: null,
11 silly cache add   name: null,
11 silly cache add   rawSpec: 'https://github.com/katzer/cordova-plugin-local-notifications.git',
11 silly cache add   spec: 'git+https://github.com/katzer/cordova-plugin-local-notifications.git',
11 silly cache add   type: 'hosted',
11 silly cache add   hosted:
11 silly cache add    { type: 'github',
11 silly cache add      ssh: 'git@github.com:katzer/cordova-plugin-local-notifications.git',
11 silly cache add      sshUrl: 'git+ssh://git@github.com/katzer/cordova-plugin-local-notifications.git',
11 silly cache add      httpsUrl: 'git+https://github.com/katzer/cordova-plugin-local-notifications.git',
11 silly cache add      gitUrl: 'git://github.com/katzer/cordova-plugin-local-notifications.git',
11 silly cache add      shortcut: 'github:katzer/cordova-plugin-local-notifications',
11 silly cache add      directUrl: 'https://raw.githubusercontent.com/katzer/cordova-plugin-local-notifications/master/package.json' } }
12 verbose addRemoteGit caching https://github.com/katzer/cordova-plugin-local-notifications.git
13 verbose addRemoteGit git+https://github.com/katzer/cordova-plugin-local-notifications.git is a repository hosted by github
14 silly tryClone cloning git+https://github.com/katzer/cordova-plugin-local-notifications.git via git+https://github.com/katzer/cordova-plugin-local-notifications.git
15 verbose tryClone git-https-github-com-katzer-cordova-plugin-local-notifications-git-2b6f5216 not in flight; caching
16 verbose correctMkdir C:\Users\User\AppData\Roaming\npm-cache\_git-remotes correctMkdir not in flight; initializing
17 warn addRemoteGit Error: not found: git
17 warn addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
17 warn addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
17 warn addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
17 warn addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
17 warn addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
17 warn addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
17 warn addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
17 warn addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
17 warn addRemoteGit  git+https://github.com/katzer/cordova-plugin-local-notifications.git resetting remote C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-katzer-cordova-plugin-local-notifications-git-2b6f5216 because of error: { Error: not found: git
17 warn addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
17 warn addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
17 warn addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
17 warn addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
17 warn addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
17 warn addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
17 warn addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
17 warn addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT' }
18 info resetRemote resetting C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-katzer-cordova-plugin-local-notifications-git-2b6f5216 for git+https://github.com/katzer/cordova-plugin-local-notifications.git
19 silly gentlyRm C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-katzer-cordova-plugin-local-notifications-git-2b6f5216 is being purged
20 verbose gentlyRm don't care about contents; nuking C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-katzer-cordova-plugin-local-notifications-git-2b6f5216
21 silly vacuum-fs purging C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-katzer-cordova-plugin-local-notifications-git-2b6f5216
22 silly vacuum-fs quitting because other entries in C:\Users\User\AppData\Roaming\npm-cache\_git-remotes
23 error git clone --template=C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/katzer/cordova-plugin-local-notifications.git C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-katzer-cordova-plugin-local-notifications-git-2b6f5216: undefined
23 error git clone --template=C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/katzer/cordova-plugin-local-notifications.git C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-katzer-cordova-plugin-local-notifications-git-2b6f5216: undefined
24 silly fetchPackageMetaData Error: not found: git
24 silly fetchPackageMetaData     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
24 silly fetchPackageMetaData     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
24 silly fetchPackageMetaData     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
24 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
24 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
24 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
24 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
24 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:123:15)
24 silly fetchPackageMetaData  error for https://github.com/katzer/cordova-plugin-local-notifications.git { Error: not found: git
24 silly fetchPackageMetaData     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
24 silly fetchPackageMetaData     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
24 silly fetchPackageMetaData     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
24 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
24 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
24 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
24 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
24 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT' }
25 silly rollbackFailedOptional Starting
26 silly rollbackFailedOptional Finishing
27 silly runTopLevelLifecycles Finishing
28 silly install printInstalled
29 verbose stack Error: not found: git
29 verbose stack     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
29 verbose stack     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
29 verbose stack     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
29 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
29 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
29 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
29 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
29 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
30 verbose cwd C:\Users\User\ionic_projects\satyam\node_modules
31 error Windows_NT 10.0.10240
32 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/katzer/cordova-plugin-local-notifications.git" "--save"
33 error node v6.10.3
34 error npm  v3.10.10
35 error code ENOGIT
36 error not found: git
37 error Failed using git.
37 error This is most likely not a problem with npm itself.
37 error Please check if you have git installed and in your PATH.
38 verbose exit [ 1, true ]
