### ISSUE TITLE
icon and smallicon not working

### ISSUE THREAD

**Issue by iamola** [katzer/cordova-plugin-local-notifications#1209]
I am using Phonegap Build with version 0.8.4 of this plugin from NPM. 
I added:

`			    icon: "file://img/icon.png",
			    smallIcon: "file://img/icon.png",`

But i still get the default Android bell icon for my app. Even when i remove both icon and smallIcon, same Bell shaped default icon. Even with res://icon.png same thing. Please help.

**Comment by iamola** [comment]
Added files to the /www, /www/img, /www/res, folder and tried all location using both file://img/icon.png and res://icon.png and nothing. :/

**Comment by tsilas** [comment]
Had this problem too. It is due to Phonegap build updating to cli-6.5.0 that happened yesterday. I downgraded to cli-6.0.0 and it worked normally.  
Simply add this to your config.xml: 
<preference name="phonegap-version"           value="cli-6.0.0" />

P.S. Could also work with other versions (for example 6.4.0) but haven't tried it since the above worked.

**Comment by iamola** [comment]
@tsila, where did you place you icons and how did you reference them?

**Comment by iamola** [comment]
6.4.0, didn't work. 6.0.0 definitely worked. The latest version that seems to work fine is: 6.3.1. Thanks @Bill

**Comment by iamola** [comment]
@rwillett Why close it if its not a fix. Its only a workaround and still needs to be fixed. -___-

**Comment by rwillett** [comment]
From reading this it appeared that this is a  phonegap issue not a plugin issue

**Comment by iamola** [comment]
Maybe, maybe not. The root cause is still not known. Maybe Phonegap changed a feature and has to be updated in the plugin. Just speaking from a quality view.

**Comment by rwillett** [comment]
Have you raised this with the PhoneGap people?

**Comment by astutesoftware** [comment]
Facing the same with cordova 6.5.0 - Icon remote and local both do not render on android pixel phone.

**Comment by sunny061** [comment]
I can also confirm that the icon and small icon are not working in cordova version 6.5.0. And I can't downgrade cordova as this always creates new issues for my app.

**Comment by rwillett** [comment]
I can confirm that it does work with Cordova 6.5.0 on local builds and Android 5 and 6. We do not use Phonegap build or have a real phone with Android 7.0 on it so we tried this with Genymotion using a Nexus 6P and API24

macpro:ts rwillett$ cordova -v
6.5.0
macpro:ts rwillett$

We have our own small icon, and you can see that it does work below. Thats the white icon with three small cars.

![screen shot 2017-03-14 at 06 15 06](https://cloud.githubusercontent.com/assets/668923/23888043/ae74141e-087d-11e7-80d5-2f4a4dec540d.png)
![screen shot 2017-03-14 at 06 13 15](https://cloud.githubusercontent.com/assets/668923/23888044/ae86d978-087d-11e7-998b-579ff2e5e4f5.png)

**Comment by dpalou** [comment]
I'm having the same problem too. I think the "res://" icons have stopped working because in the latest Cordova releases the icons are copied to res/mipmap folders instead of res/drawable. This could be solved with a hook, but Phonegap Build doesn't accept them so IMO it should be fixed in this plugin.

I tried using "file://" instead, but for some reason it isn't working for me either. Maybe it's because of the image size (pixels), but I tried different sizes without success (36x36, 48x48, 72x72, 96x96, 144x144, 192x192). I debugged the code a bit (getUriFromAsset) and the file is found and copied, but it's still not shown. Any ideas?

**Comment by dpalou** [comment]
I created a Pull Request to fix the "res://" problem:

https://github.com/katzer/cordova-plugin-local-notifications/pull/1292

I tested it and it seems to work, but it would be fine if someone could review it since I haven't developed for Android since Android 4.3 :)

**Comment by Topiya** [comment]
@rwillett 
Can you please let me know what should be the icon image size and what should be the image path?
