### ISSUE TITLE
Ionic: Cordova local notification call on specific condition

### ISSUE THREAD

**Issue by hariomtestid** [katzer/cordova-plugin-local-notifications#1228]
Hello everyone! i am new with ionic framework. Currently  working on Ionic iOS app i need to implement local notification every time when my order is success or change in order status. For this i have installed cordova local notification.

What i need is to check every minute whether logged in user status changed or not if status change then send notification to user .

**Comment by rwillett** [comment]
This appears to be a coding design problem that you need to solve. 

Once you have worked out what you want to do and how to check if user is logged in then create a local notification.

**Comment by hariomtestid** [comment]
@rwillett , I have made condition for checking logged in user order status but i need to check every 1 minute or or every time order status of logged in  user,  whether app is in background state or foreground than send notification immediately. but i am unable to check status every time and send notification. If i schedule notification every minute  than it will send same notification every minute.

**Comment by rwillett** [comment]
This is not an issue with local notifications.

You need to use a plugin that works in the background to check the status, This can be very difficult on IOS as Apple does NOT want you doing background processing apart from a very few set of specific cases such as geolocation and audio processing.

If your app is in the background, then it will get suspended quickly. That is a feature of IOS and there is nothing you can easily do. 

Your problem is nothing to do with local notifications, you have to rethink what you are trying to do and find a new approach. You have to understand what you are allowed to do with IOS and what you are not allowed to do. These rules are made by Apple and are not made by this plugin.

This is the only plugin I know of that might (or might not) help.

https://github.com/transistorsoft/cordova-plugin-background-fetch

Note it ONLY allows about 30 secs of background processing every 15 mins. That is because Apple restricts what you can do.

You need to change your design to accept what you can and cannot do with IOS.

**Comment by stevesum** [comment]
Rob has right.
Addition information about the background fetch, that you can't provide
that the fetch will fired on every 15 minutes. You can define only the
fetch won't be fired by the operation system more often than X minutes.
What means, the fetch is timed totally by the operation system with a very
complex (and not public) logic what will consider for example the user
behaving (how often use your app, when usually open it, what the state of
the battery, etc.).
In a bad situation the fetch could delayed for 48 hours also.

2017-03-01 8:02 GMT+01:00 Rob Willett <notifications@github.com>:

**Comment by hariomtestid** [comment]
Thank you so much @rwillett i'll try this.

**Comment by rwillett** [comment]
As @stevesum has said, the background processing plugin has severe restrictions on it. These are placed by Apple and not by the plugin.

You need to think through your logic. There is no plugin that will allow you to check for a login every 60 secs whilst in the background. You also do not want to do this. If will kill your battery. 

If the app is in the background then it is suspended and what differerence does it make if you are logged on or not? You can't make (easily) make any HTTP calls, nothing is working. Why do you need to know if the the suspended app is logged on. The user can't do anything with the app as its in the background, the app can't do anything as its suspended. So leave it. 

When the app comes into the foreground is when you need logic. You are fighting the design of Apple (and Android). You will lose that fight. There is zero chance Apple will allow you to submit an app that does what you want to do. The review process will catch it and reject it.

**Comment by keithdmoore** [comment]
Sounds like you just need to check to see if the user is logged in upon app start or resume and/or prior to making a http request.  If they are not logged in, you can just open an alert, popup or modal indicating as such.  Then maybe take them to the login screen.

**Comment by rwillett** [comment]
Closed
