### ISSUE TITLE
setInterval not working in background

### ISSUE THREAD

**Issue by AriffAzmi** [katzer/cordova-plugin-local-notifications#1244]
Hi,

First of all thanks for the great plugin. I face a problem for setting interval to running in background. For example, i want to do interval to checking on my server. If conditions is meet, then push the notification. So far if im closing the app, it does not work. Did you have any example for this case ?

Thank you

**Comment by rwillett** [comment]
First of all fill out the template in #1188.

Secondly you need to explain a little clearer about what you are trying to do.

If you are trying to use this plugin to initiate background processing to check a server, this is not the plugin to do it.

**Comment by AriffAzmi** [comment]
Hi Robert,

Pardon me because im does not know the template for report an issue and
also my bad english.

I give you my sample code regarding to this issue.

// Set every 3 second, fire to server
setInterval(function(){

       $.post('url_to_server', function(respons){

                If(respons==true){

               cordova.plugins.notification.local.sc   hedule({

    id: 1,
    text: "Single Notification",
    sound: isAndroid ? 'file://sound.mp3' : 'file://beep.caf',
    data: { secret:key }
});

                }
        },3000);

This is what im trying to do

**Comment by rwillett** [comment]
Still fill the template in using #1188 as that tells us what you are trying to do, what your environment is, what OS you are using.

We have no idea if you are using Android or IOS.

1. As a first pass, since it's still not clear what you are doing, this will never work on IOS when the app is in the background as your app will not run setinterval. All timers get suspended. Also your $.post will not work either. I'm not sure about Android as we don't do setinterval as it doesn't work on IOS

2. Even if this did work, your battery will be dead very quickly as you are constantly hitting the server.  

3. You cannot 'easily' have this code working on IOS as Apple will not let you do it. Once your app is in the background it will become suspended. IOS10 is very aggressive about suspending your apps. There are ways to get around this if and only if your app does not go through the Apple app store. These ways will not work if your app hits the Apple store. It WILL be rejected.

You need to think again what you are doing and why you are doing it.

Rob

**Comment by rwillett** [comment]
Closed as no update from original poster.
