### ISSUE TITLE
Feature Request: Local notification with action button

### ISSUE THREAD

**Issue by abhinituk** [katzer/cordova-plugin-local-notifications#1258]
Is it possible to generate local notification with action buttons using this plugin? I have tried [https://github.com/elizabethrego/cordova-plugin-local-notifications](https://github.com/elizabethrego/cordova-plugin-local-notifications) but it does not work well?

**Comment by rwillett** [comment]
Not at the moment,

**Comment by abhinituk** [comment]
Any workaround to generate local notifications with action buttons?

**Comment by rwillett** [comment]
No.

**Comment by abhinituk** [comment]
I have tried [https://github.com/elizabethrego/cordova-plugin-local-notifications](https://github.com/elizabethrego/cordova-plugin-local-notifications) but it works well for Version 0.8.2, but after upgrading it to 0.8.4, it can not generate local notification with action buttons.  As mentioned by elizabethrego in repository: "**NOTE: This is totally outdated, but it'll work fine until Katzer releases 0.9 (where my updated changes have been merged). **", can you have a look at it?

**Comment by rwillett** [comment]
I'm not the author of the plugin. I'm helping run the issues here. 

The local notification plugin is being completely rewritten for ios10. There is no timetable for the release of the new version of the plugin. Its not clear if these merges will be incorporated in the new version of the plugin.

**Comment by abhinituk** [comment]
How can I raise this issue to author of the  plugin?

**Comment by rwillett** [comment]
You already have. 

@katzer is working on the new plugin for IOS 10. He does this part time as its a free plugin. I'm running this part of the board and helping to give him more time to work on the plugin. He has other work to do as well. 

His focus is on the new development which is taking time. He does read this board but rarely comments at the moment. Thats his choice.

The plugin https://github.com/elizabethrego/cordova-plugin-local-notifications has been around for some time, the merges have not been made and I suspect they will never be made as the code base has moved on significantly since then. 

As this is open source and completely free, you can update the plugin yourself, you can fork it and work with somebody else to do it. I'd be surprised if the mods are ever merged though.

**Comment by smgjreinieren** [comment]
Any update yet?

**Comment by rwillett** [comment]
There is no timetable for any update. 

If its that important to you, look at forking and funding the changes yourself.

**Comment by katzer** [comment]
Has been added with 0.9-beta
