### ISSUE TITLE
member 'at' is truncated when returned by all get methods tested

### ISSUE THREAD

**Issue by garygriswold** [katzer/cordova-plugin-local-notifications#1259]
When I schedule a notification by setting at with a date object in the near present, get, getAll, getScheduled and getTriggered return an at value such as "at":1490923535.  This is too short to be a valid current time, which at this moment is: > a=new Date().getTime() -> 1490923535184.

at is being truncated to a 10 digit number.  Since a 32 bit word holds 2147483648 (a 10 digit number). I suspect that the value of at is being passed into a 32 bit word at some point.  This problem was observed on the iOS platform.

cordova 6.5.0
platform iOS 4.3.1
de.appplant.cordova.plugin.local-notification 0.8.4
macosx 10.12.4

Other plugins:
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-console 1.0.6 "Console"
cordova-plugin-device 1.1.5 "Device"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-sqlite-ext 0.10.4 "Cordova sqlite storage plugin with extras"

**Comment by garygriswold** [comment]
I guess this is not a bug, but rather the get methods return an 'at' member in seconds, not milliseconds.  A correct datetime can be determined to the second by multiplying the 'at' value times 1000 before creating a date object.

**Comment by rwillett** [comment]
There is a difference in the way you schedule time and the time values that come back. 

As you found, they come back in millisecs but you send them in secs. 

This is a pain, and I'm not sure if its IOS or the plugin, but once you know about it, its easy to resolve. 

Part of the problem is that the UNIX epoch date is/was defined in secs and the original UNIX timestamps didn't report anything less than seconds. That has carried over for the last 40+ years. Legacy code is great :)
