### ISSUE TITLE
This plugin is abandonware and should be removed from Ionic web site.

### ISSUE THREAD

**Issue by esmiralha** [katzer/cordova-plugin-local-notifications#1270]
This plugin has 114 open issues and no changes have been made in the past 12 months. It should be removed form Ionic web site and replaced with a better fork.

**Comment by rwillett** [comment]
You are welcome to do so. 

Please let us know where the fork is located.

**Comment by rwillett** [comment]
Since I've now woken up, l'll answer this properly. I'll make this clear that I am not the author but help on the site to give the author time to do development of the next version of this plugin.

1. This plugin has not been abandoned. Read the very first sentence of the very first paragraph on the very first page.  Here it is again

  ```Its been a while that the plugin has received major updates and bug fixes. My (free)time is limited and I have multiple projects to maintain. Once I've updated my background-mode plugin the local-notification plugin will get an official release supporting ios10. The ios10 branch will be merged into the master as well.```

If you had taken the slightest interest in reading any of the issues you would be aware that Apple has changed the underlying local notifications system in IOS 10. This has meant that it requires a significant rewrite JUST for IOS 10. 

Work is ongoing rewriting the plugin. Just because it is not going at the speed you want, that does not give you the right to declare this as abandonware based on zero knowledge. 

2. This plugin has nothing to do with Ionic. They choose what to put on their pages, they choose whether or not to incorporate it into their plugins. They choose whether to put it on their plugin page. 

3. The number of open issues has no reflection on the state of development. Is 114 too much or too little? I know some highly active projects with hundreds and thousands of open issues, I also know some with very few. How many open issues do you think Firefox has? 

4. Many of these 'open issues' are enhancements, there are 35 of them, so thats around 25%,  e.g. Multiline text in Android notifications,  more complex scheduling systems, HTML images. These may or may not be done but they are left open so that people are aware of them. I know some of these are duplicates but I do not have time to de-dupe them.

5. If you had looked properly, you would have seen that there is another release this last year specifically for IOS10.  It is an interim release, it's purely to fix (or apply a plaster) the issues of running under IOS10. 

6. This plugin is donated for free. It costs you nothing, you can take it, fork it and fix the problem yourself. Nobody is stopping you. So since **you** think it is abandonware, **you** take it, **you** fix the issues with IOS10, **you** make sure that it still works with Android 4, 5, 6 and 7, **you** make sure it works with Ionic 1, Ionic 2 and now Ionic 3. **You** update the documentation. **You** do that for free. Have **you** made any contribution to the plugin or helped in anyway? So lets see **you** step up, lets see **you** fork this as **you** think its abandoned. 

So before you start making stupid statements, I suggest you look a little bit further into whats going on. 

Rob

**Comment by stevesum** [comment]
👍

2017-04-13 10:15 GMT+02:00 Rob Willett <notifications@github.com>:

**Comment by rwillett** [comment]
Since the original poster hasn't bothered to reply, closed.
