### ISSUE TITLE
Notifications not working in iOS 10.3 on physical device

### ISSUE THREAD

**Issue by bmcorum** [katzer/cordova-plugin-local-notifications#1279]
**Plugin version:** 0.8.5-dev
**Platform:** iOS
**OS version:** 10.3.1
**Device manufacturer / model:** Apple iPhone 6s
**Cordova version (cordova -v):** 6.5.0
**Cordova platform version (cordova platform ls):** iOS 4.3.1

**Plugin config**
**Expected Behavior**

Notifications to show in notification tray

**Tell us what should happen**

Notification should fire when schedule and viewable from notification tray

**Actual Behavior**

No notification is fired

**Tell us what happens instead**

No notification get fired or shows in tray

**Steps to Reproduce**
**Reproduce this issue; include code to reproduce, if relevant**

var d = new Date();
var now = d.getTime();
cordova.plugins.notification.local.schedule({
    id : "2",
    at: new Date(now + 10000),
    text : "Testing 1..2..3"
});

**Context**
**What were you trying to do?**

Get notification to fire based on a schedule when app is running in background.

**Extra**
Same code works when building and running on simulator with iOS 10.3 but not when installing on physical device. This is the last piece I need to finish my app and get it submitted to the Apple Store. Any advice would be greatly appreciated. Thank you.

**Comment by rwillett** [comment]
Are you trying to schedule the notification when the app is in the background or scheduling when the app is in the foreground, then putting the app into the background.

There are no issues scheduling in the foreground, moving the app into the background and waiting for the notification. 

I have posted actual code to demonstrate this working yesterday. Search for it.

**Comment by rwillett** [comment]
Also see #1272

**Comment by bmcorum** [comment]
@rwillet I have tried scheduling in background and foreground and then waiting for notification while app is running in the background and neither work. I have already read all of #1272 before I opened my own issue. I copied your example line for line and still does not work on a physical device. I will try a new clean test app and see if maybe something got out of sync or a plist entry might be fouling me up. Any other suggestions would be appreciated. Thank you.

**Comment by rwillett** [comment]
The code in #1272 is working code pulled out of a working 10.3 IOS system. It also works on Android.

Something else is wrongly configured elsewhere. Difficult to know what.

**Comment by bmcorum** [comment]
@rwillett it seems I did manage to show how really foul up my project. I started a completely new project with the iOS10 branch and it all appears to be functioning. I do have a few questions about the ability to schedule notifications when the app is in the background. I use geolocation while app is running in the background using cordova-background-geolocation-lt so it keeps my javascript running. It seems as though the notifications don't always get schedule and when the do they seem really delayed. I might schedule one notification to happen with in a few seconds of an location event but I might not get the notification for 10 or minutes. Any ideas?

**Comment by rwillett** [comment]
As far as I know, cordova-background-geolocation-lt does NOT keep your JavaScript running all the time in the background. If it did, you'd have no battery left. It has some low level C (Swift?) code that works as needed and makes some very limited callbacks to JavaScript.

We use the paid-for version. it has the ability to run some functions in the background, e.g. GPS and sending stuff to servers, but IOS doesn't allow you to run JavaScript in the background all the time. We don't tend to use them though.

If I recall correctly later versions of the paid for plugin use an additional plugin that gives you a little bit of time, you may (or may not) have access to this page

https://github.com/transistorsoft/cordova-background-geolocation/wiki/Background-Tasks

which explains more.

Its entirely possible that you only get a few seconds of background processing every 5-10 mins which would explain your scheduling issue. This is something you need to take up with Chris who is the author of the plugin. You are pushing what you can do with IOS. My understanding is that Chris has done as much as he can do and any limitations are due to IOS and not him.

**Comment by bmcorum** [comment]
@rwillett thanks. I figured it was more of an iOS thing. I am starting to realize that what I am trying to accomplish may not work with iOS very well due to restrictions and such.

**Comment by rwillett** [comment]
Do you have notifications working no on a physical device?

**Comment by bmcorum** [comment]
Yes. Sorry meant to close this issue

**Comment by rwillett** [comment]
What exactly did you do? Please log so other people can earn from your issue.

Thanks

Rob

**Comment by bmcorum** [comment]
I started from a completely new Cordova project and removed the "every" option for the schedule object.

**Comment by rwillett** [comment]
The every option wasn't in the code you showed us.

**Comment by bmcorum** [comment]
No but I was having issues with that as well. Anytime I try to use the every option the notification won't work

**Comment by jruizsulime** [comment]
I've iOS 10.3.3 and notification local doesn't work, only in simulator, not in physical device :(
