### ISSUE TITLE
No notification overlay appears on Android 8.0.0 

### ISSUE THREAD

**Issue by ruben82** [katzer/cordova-plugin-local-notifications#1403]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## My Environment

* Plugin version: 0.8.5
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: Nexus 5X
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```): Android 6.3.0
* Plugin config
* Ionic Version (if using Ionic): 3.14.0

## Expected Behavior

When I call in background mode
```
this.localNotifications.schedule({
        id: 1
        , title: "Prova"
        , text: "Testo"
      });
```
a overlay notification should appears.

## Actual Behavior

Nothing is showed on Android 8.0.0. All works on Android 7.0

## Steps to Reproduce

Execute that code when app is closed 

## Context

I tried to reinstall everything... but with no result

## Debug logs

No error is logged

**Comment by stevesum** [comment]
On Android 8 in the Builder.java have to extend the
NotificationCompat.Builder with a new property:

builder = new NotificationCompat.Builder(context)
        .setPriority(NotificationCompat.PRIORITY_HIGH)

        ....;


BR,
Steve

2017-10-24 12:13 GMT+02:00 Ruben Rocco De Luca <notifications@github.com>:

**Comment by ruben82** [comment]
@stevesum Thanks for replying me.
Is this native code not added automatically by the plugin then?
Do we do this manually, don't we?

**Comment by stevesum** [comment]
Yes, this is a 'missing' in the native code of the plugin. Unfortunately
the maintenance is not so fast, so you have to modify this code after you
added to your project, or wait while the following pull request will
applied on the project:
https://github.com/katzer/cordova-plugin-local-notifications/pull/1389

BR,
Steve



2017-10-24 13:03 GMT+02:00 Ruben Rocco De Luca <notifications@github.com>:

**Comment by ruben82** [comment]
Hi @stevesum no way... Tried PRIORITY_MAX too with no success...
Did you try it on sdk 26 (Android 8.0.0)?

**Comment by stevesum** [comment]
Hi,

Yes we tried the solution on sdk 26 also. We had some problem the
notification was appeared in the info bar, but was no overlay appeared.

After we checked the android API we figured out the notification get
overlay only if the priority is hight and the notification have small icon
and sound together with the text.

We forked the plugin from the X branch (
https://github.com/katzer/cordova-plugin-local-notifications/tree/x),
because we have to use it both iOS, Android and Windows, and we modified
only the src/android/notification/Builder.java
<https://bitbucket.org/ovitas-felleskatalogen/cordova-plugin-local-notifications/commits/1c8a6d7bf77c411d77ab677468270942165cdaa6?at=master#chg-src/android/notification/Builder.java>
with
the following

builder = new NotificationCompat.Builder(context)

                 .setDefaults(0)

+        .setPriority(NotificationCompat.PRIORITY_HIGH)

                 .setContentTitle(options.getTitle())

                 .setContentText(options.getText())

                 .setNumber(options.getBadgeNumber())

                 .setTicker(options.getText())

                 .setAutoCancel(options.isAutoClear())

                 .setOngoing(options.isOngoing())

                 .setColor(options.getColor());


And we use the following schedule data:

/**     * @private     * return with a second alert object     *     *
@param {Number} id     * @param {Date} at     * @param {String}
message     * @param {JSON/null} data     *     * @return     */
getAlert: function(id, at, message, data) {        return {
id: id,            text: message,            at: at,            badge:
1,            ongoing: true,            smallIcon:
'res://statusbaricon',            color: 'e11f25',            data:
data        };    }


I hope these information could help you.

BR,
Steve

2017-10-25 10:51 GMT+02:00 Ruben Rocco De Luca <notifications@github.com>:

**Comment by ruben82** [comment]
No way @stevesum! I'm stuck with this issue... I tried to change java source code with no success.

**Comment by katzer** [comment]
@ruben82 I've merged 0.9-beta into master - the support for Android 8 is basic yet. I am working on it.

**Comment by amitkhare** [comment]
Any luck? I'm stuck here too.

**Comment by Darrenchand** [comment]
Same!!

**Comment by salouri** [comment]
why closing it if its not solved yet! We have the same problem here and Android Oreo has been out for a year and no fix yet?!

**Comment by Tawpie** [comment]
@salouri have you tried 0.9.0-beta3? It works on Oreo for me, but look for another issue regarding notifications cancelled after a phone restart. There is a fix for that too, but it's not yet pulled so you have to make the change manually.
