### ISSUE TITLE
iOS : Silent notifications not silent ?

### ISSUE THREAD

**Issue by nilebma** [katzer/cordova-plugin-local-notifications#1447]
## Your Environment

* Plugin version: 0.9.0-beta.1 
* Platform: iOS
* OS version: 11.1
* Device manufacturer / model: iPhone 6s (iPhone 8,1)
* Cordova version : 7.1.0
* Cordova platform version : ios 4.5.0
* Plugin config : default

## Expected Behavior

I am trying to trigger (and update) a notification _silently_ on iOS, when the app is on _foreground_. From my understanding, a _silent_ notification should not be displayed on the screen when it is triggered (or emit any sound or vibration). It should only be visible when opening the notification tray.

## Actual Behavior

Whatever combination of options I use, the notification either displays on the top of the screen, or seems to be not triggered (no notification in the notification tray), without any errors. I also tried to play with the _foreground_ option to _false_ without success.

## Steps to Reproduce

I use the following code :

`
cordova.plugins.notification.local.schedule(
   {
      id : 1,
      title: "Hi !",
      text: 'That was pretty easy...',
      sound: false,
      vibrate: false,
      silent: true
   });

`

## Context

I have no idea if i use the "silent" option correctly (btw I could really not find any documentation about it). Maybe the silent option is not even appropriate here. I tried other options like putting _foreground_ to _false_, but nothing worked for me. 

My goal is to emit (and update) a notification silently when the app is on foreground, without the user noticing it. When the user put the app to the background, they can see the state in which they left the app by looking at the notification.

Thanks a lot if you could provide any hint here :-) And thanks to @katzer and all the people developing this plugin, which is working great (despite this small issue) !

**Comment by GeneralUSA** [comment]
I wish someone experienced would answer this for you, because **I am having same issue**.
cordova.plugins.notification.local.schedule({
   title: ' title ',
   text: 'text\'s words',
   foreground: false,
   every: "minute",     // for testing, eventually every week; not sure how to let them select the day
  });

**Comment by GeneralUSA** [comment]
I found my resolve at the following issues:
https://github.com/katzer/cordova-plugin-local-notifications/issues/1412
https://github.com/katzer/cordova-plugin-local-notifications/issues/1413
https://github.com/katzer/cordova-plugin-local-notifications/issues/1493

My end code, which I am still tweaking, works with this test base below, and won't fire until the app is closed:

cordova.plugins.notification.local.schedule({
   title: ' title ',
   text: 'text's words',
   foreground: false,
   silent: true,
   trigger: { every: 1, unit: 'minute' }  , // for testing, eventually every week; not sure how to let them select the day
});

trigger needs v0.9-beta

**Comment by rwillett** [comment]
@GeneralUSA Raise a new issue, make sure you fill the template in. There's not enough information here and this is for silent notifications. 

I can see an immediate problem in that you have an apostrophe in the text string.

**Comment by GeneralUSA** [comment]
@rwillett my issue was the exact same issue as @nilebma. I figured most of it out though.

**Comment by rwillett** [comment]
@GeneralUSA 

You have commented on two things, one silent notifications and then you stated "My end code, which I am still tweaking, works with this test base below, and won't fire until the app is closed:" 
That's a different problem. If the code has nothing to do with the issue, I suggest you delete it so it doesn't confuse people.

**Comment by GeneralUSA** [comment]
@rwillett I started out by saying that I had resolved the issue. I'm not sure of all the other points you are raising. I am a learner programmer and as such, when I think I've resolved something, I do my best to offer feedback from a learners POV. As far as I am concerned, my issue was closed before I posted the second comment. Not sure of why we are having this back and forth. Thanks for your concern though. Should I need further assistance on an issue I think is actually still an issue, I will start a new thread. At this point, if you are experienced, which I believe you are because I've seen your name before, then perhaps you or @katzer or someone else can just verify that the code I posted works. As far as I am concerned, the issue is closed for me. As far as @nilebma is concerned, he would have to answer if my post helped him as well. Thanks again for your follow up.

**Comment by rwillett** [comment]
@GeneralUSA 

As I stated previously, you raised two items, one about how you solved the problem relating to "silent notifications" and the other about a piece of code that doesn't work. The second issue has nothing to do with the first. It is considered good etiquette when using Github and other similar thread based systems to keep the thread on-topic, i.e. as the thread is about Silent Notifications on IOS, to keep the thread about this specific topic. 

You 'polluted' or 'hi-jacked', or went off-topic to bring in another wholly unrelated issue, about a piece of code that doesn't work until the app is closed. As one of the administrators for this board, I try to keep the threads on-topic and relevant, so that when people come back to look for help, a thread is consistent and only discusses what is relevant to the thread. Your second comment is wholly off-topic, as it is completely unrelated to the silent notifications, so I asked you to raise this as a separate thread. I had no idea you managed to resolve your second issue as you never said so. We can only work on what we see in front of us.

As you are a self described learner programmer, these are areas you need to understand and learn about. Your comment "someone else can just verify that the code I posted works" is an example of how you are going off-topic yet again. Having to explain to you about thread etiquette is also off-topic, but as you are new to this, its worth taking the time to explain to you how things work, so that in future you (and other people) understand more. As an admin, it's very frustrating having people post comments in threads that meander and wander away from the topic in hand. Hi-jacking threads is normally considered bad.

Remember that there is a search system attached to Github, and that if somebody, perhaps another beginner, searches for "Silent Local Notifications IOS", they will probably hit this thread, your code and your comments may confuse them as to the solution. Thats why we try to keep threads very focussed and on-topic. Thats why we insist on a template, so that the next person coming along has an idea what the problem is and whether or not it is relevant to them. 

I hope this helps and you now understand more about how to work with this particular forum. Other forums may have different ways of working, some may simply delete your posts as off-topic, or move them, others have a very laissez-faire attitude.

Rob

**Comment by GeneralUSA** [comment]
@rwillett I found @nilebma question because that WAS my question. I fail to see how I polluted anything since my resolve helped me to create a "Silent Local Notification" on iOS. Perhaps, it is in my understanding of "silent" that we are going back and forth. But reading the initial concern by @nilebma that was also my concern.

"_From my understanding, a silent notification should not be displayed on the screen when it is triggered (or emit any sound or vibration). It should only be visible when opening the notification tray._"

 I too did not want the notification to fire/trigger/show until my app closed. So I fail to see how I've polluted this -- except w/the conversation that you and I are having.

I did not say anything about code that didn't work. Not sure what you are talking about. 

I'm done with this issue and I have not polluted the channel. Perhaps this "bickering" that you and I find ourselves engaged in has hijacked the channel though, but not initiated by me. I was excited to have been able to resolve the issue and shared my resolve. That was ALL that happened on my end.

I appreciate your support as well as the other experienced programmers who offer support. It is a great learning opportunity. If you want the last word, have it.

**Comment by rwillett** [comment]
I give in. Sort your own problems out in future.

**Comment by katzer** [comment]
The behaviour of a _silence_ notification depends on the native system. For iOS it means that if the phone is running in foreground and receives a system call about a triggered notification, the plugin will just fire the _trigger_ event while no banner will pop up and no notification will be added to the notification center.
