### ISSUE TITLE
Not able to Unsubscribe events

### ISSUE THREAD

**Issue by pandeeswaran** [katzer/cordova-plugin-local-notifications#1569]
Event can't able to unsubscribe by using notification.un methods.
When using notification.on methods its called multiple time based on registered events count.

**Comment by ismailocal** [comment]
+1

**Comment by rwillett** [comment]
No template, no idea what is being requested. The template is there for a reason.  Use it.

**Comment by leo4444** [comment]
I was with the same problem and I could solve it ...
I leave this that may be useful for others:

// Method where the local notification is generated
generateNotification (event: any) {

   this.localNotifications.schedule ({
            id: 1
            title: "Title Notification"
            text: "Description"
   });

   var callback = (event, callback) => {
            // Action to be executed when clicking on the notification
   }

   // Clicking on the notification will trigger the previous callback;
   this.localNotifications.on ('click', callback);

   // This line MUST NOT be located next to the .on method,
   // Since if that happens, the click event is unsubscribed before the callback is triggered
   // Must be used in a place where the context of the callback variable is not lost
   // The most common would be to use it in a method that is called within the 
   // Landa expression of the callback variable
   this.localNotifications.un ('click', callback);
}

I hope this helps you!

**Comment by rwillett** [comment]
Interesting. 

You could put it in a timeout with a 0 millisec value so it gets called at the end.
