### ISSUE TITLE
Does local notification plugin schedule works after reboot?

### ISSUE THREAD

**Issue by swa06** [katzer/cordova-plugin-local-notifications#1573]
I am using the local notification plugin for scheduled notification every hour. I have installed version 0.8.5 since I could not install the master version for compatibility issue with crosswalk plugin. Could anyone please tell me if the scheduled notification works after the phone is rebooted.

* Plugin version: 0.8.5
* Platform: android
* OS version: 4.1-7+
* Device manufacturer / model: Samsung
* Cordova version (```cordova -v```): 7.1.0
* Plugin config : 
<plugin name="de.appplant.cordova.plugin.local-notification" spec="^0.8.5" />
* Ionic Version (if using Ionic) 3.1.7

@katzer

**Comment by rwillett** [comment]
We have had significant problems with the Crosswalk plugin. We never managed to get it to work reliably. We constantly had white screens of death which is caused by the web server crashing. There are hacks (and bad ones at that) to try and get around these crashes. We gave up though.

The Crosswalk plugin is great in principle, but we found it very, very unreliable. Check the Apache incident log for the issues. You may find it works for you, but we abandoned the work and went back to the standard Webview.

The older notification plugin may or may not work with what you want to do. It's not supported anymore so you'll find that you get further and further behind on fixes.

**Comment by swa06** [comment]
@rwillett Thank you for your expert opinion . In my case using crosswalk was a default option for webview since my app needs to support lower api levels like 16.

**Comment by rwillett** [comment]
If you're supporting stuff back to API 16 (Android 4.1) you could have other issues. Thats really old (Oct  12?). Thats a five year old OS and stuff moves on. I recall we tried it on Android 4.3 and had similar reliability issues but your system may work well. However I know other groups have had similar bad experiences with Crosswalk, don;t know anybody who has made it work reliably for them, but everybody is different.

Rob
