### ISSUE TITLE
Notification with Progressbar remove or update

### ISSUE THREAD

**Issue by sand4r** [katzer/cordova-plugin-local-notifications#1623]
I created a notification with a progress that I can properly update. When I reach 100% I would like to show a message "Download completed". Unfortunately I could not find a documentation on how to replace the progress in the notification or how to remove the notification and add another. If it's possible could you update the documentation?

## Your Environment

* Plugin version:
    "@ionic-native/local-notifications": "^4.7.0",
    "cordova-plugin-local-notification": "^0.9.0-beta.2",

* Platform: Android 
* OS version: 8.1
* Device manufacturer / model: LGE 4
* Cordova version (```cordova -v```): 8.0.0
* Ionic Version (if using Ionic): 3.20.0

**Comment by JhonnyJason** [comment]
Hello
I do have the same scenario. I would like to indicate the progress of a program outside of the App. 
So I make use a progress bar and encounter 2 problems:

When the Progress Updaterate is too fast, the App becomes killed by Android.
I cannot kill or cancel the Notification.

I assume that I have to use an Id for the certain notification when I create it.
I use the same Id to update the notification.
And would expect that:

`notificationHandle.clear({id: knownId})`

will clear the notification.

Appearently I'm missing something^^. 
Would be greatful for clarification :-)

Thnx!

**Comment by JhonnyJason** [comment]
New Information:

If I call 

`notificationHandle.clearAll()`
or
`notificationHandle.clearAll()`

I manage to clear the notification.
It appears that I cannot reference it throught the Id.

Oddly also the function 
`notificationHandle.getIds()`

returns undefined :-(

I initialize the Notification using:
`var notification = {
sticky: true,
clock: false, 
vibrate: false, 
id: 5,
title: "title",
text: "Text",
progressBar: {value: 0},
actions: [ { id: 'play', title: 'Play', type: "button"},
                { id: 'pause', title: 'Pause', type: "button"},
                { id: 'quit', title: 'Quit', type: "button"} ]
}

notificationHandle.schedule(notification)`

And update it like this:
`var updateObject = {
id: 5,
progressBar:{value: progress}
}

notificationHandle.update(updateObject)`

And this update process appears to work even though there are no existing Ids^^
hummm... what do I do wrong?

**Comment by guyromb** [comment]
You use it correctly (first schedule, and interval using update).

When you want to finish the progressbar you can do the following:
1. Schedule a new one with the same ID (it will overwrite it)
2. set autoClear: true (so sticky can be removed)

**Comment by spbala07** [comment]
@guyromb Can you post some examples?

**Comment by Fever905** [comment]
That is not the best solution, cuz even when its set to done the tirmer will run on it.  Can we not display the timer somehow?

**Comment by kevinciang1006** [comment]
I had a similar problem like @JhonnyJason mentioned but instead of using 
`notificationHandle.clear({id: knownId})`
i used 
`notificationHandle.cancel({id: knownId})`

so i tried tinkering with notificationHandle.
Turns out when i tried this
`
// set sticky to false
notificationHandle.update({
      id: 5 // the knownId to cancel
      sticky: false,
    });

// then canceling it
notificationHandle.cancel(knownId); // or using notificationHandle.clear({id: knownId})
`
It works in my case. I manage to clear the notification per id

### My Environment
Plugin version:
"@ionic-native/local-notifications": "^5.24.0",
"cordova-plugin-local-notification": "^0.9.0-beta.4",

Ionic:

   Ionic CLI                     : 5.4.4 
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.0.1
   @capacitor/core : 2.0.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 7.1.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, (and 10 other plugins)       

Utility:

   cordova-res : 0.8.1
   native-run  : 1.0.0

System:

   NodeJS : v10.15.0 (D:\Documents\NodeJs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

Tested Platform: Android
OS version: 9.0
