### ISSUE TITLE
Build Failed for android-targetSdkVersion 26

### ISSUE THREAD

**Issue by ivac2099** [katzer/cordova-plugin-local-notifications#1645]
##  Environment

* Plugin version: 0.8.5
* Platform: Android
* OS version: Windows 7
* Cordova version (```cordova -v```): 8.0
* Cordova platform version (```cordova platform ls```): android 7.0.0

##  Behavior

_Build Successful for android-targetSdkVersion=25_
_**Build Failed** for android-targetSdkVersion=26_

_Google Play Console has been demanding version 26 since August_

**Comment by ivac2099** [comment]
Thank you very much. Version 0.9.0-beta3 worked for me.

**Comment by p-sebastian** [comment]
Doesn't work for me @Tawpie , I switched to beta.3, but it keeps taking the last sdk available shown by 
> cordova info

which for me is

> id: 4 or "android-26"
     Name: Android 8.0.0
     Type: Platform
     API level: 26
     Revision: 2
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in, AndroidWearRound, AndroidWearRound360x360, AndroidWearRound390x390, AndroidWearRound400x400, AndroidWearRound454x454, AndroidWearRound480x480, AndroidWearRoundChin320x290, AndroidWearRoundChin320x300, AndroidWearRoundChin360x325, AndroidWearRoundChin360x326, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare240x240, AndroidWearSquare320x320
 Tag/ABIs : android-tv/x86, android-wear/x86, google_apis/x86, google_apis/x86_64, google_apis_playstore/x86
----------
> id: 5 or "android-27"
     Name: Android 8.1.0
     Type: Platform
     API level: 27
     Revision: 1
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : no ABIs.
----------
> id: 6 or "android-P"
     Name: Android P (Preview)
     Type: Platform
     API level: P
     Revision: 2
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : google_apis/x86, google_apis_playstore/x86

**I deducted this from the error I got which is:**
> Plugin doesn't support this project's android-sdk version. android-sdk: android-P, failed version requirement: >=26

I had to delete the android-p sdk, in order to be able to build the plugin, and if by any chance you have the "google API sdk", those will take preference so you have to delete those too.
And setting **targetSdkVersion** doesnt seem to do anything

**Comment by ivac2099** [comment]
updating existing project won't work for me as well. i have to setup everything from scratch. Starting from setting up new windows.
