### ISSUE TITLE
General question: Should I build an app based on this plugin?

### ISSUE THREAD

**Issue by Kyleeeez** [katzer/cordova-plugin-local-notifications#1683]
I'm building an app based on notification and reminders.
Can I trust this plugin or is it a bit risky?

**Comment by coffeverton** [comment]
I would say that you can trust, but it depends.

Right now, I am having problems with latest versions of Android (8) and IOS - the problem is that the custom sound notifications does not work. Instead, it plays the default notification sound.
For our project it does not affect much, but you must consider your audience.

Also, this is the only plugin to send local notifications available for cordova/phonegap. You can try to use push to send notifications, but in this case, the device must have internet access.

**Comment by Tawpie** [comment]
echoing @coffeverton The plugin is very effective for some but not all applications, although there are workarounds for the plugin shortcomings. Notably if you look through the issues you'll see challenges with getting the `every` triggers to work, the plugin does not appear to receive trigger or click events from the OS when the app is not foreground, it's not updated to fully support Android 8+. And lastly the primary (sole?) maintainer has other obligations so pull requests tend to languish. All that means is that you must be a bit more watchful and manually incorporate fixes as they appear here rather than rely on the maintainer to incorporate them in a new version.

We still rely heavily on the plugin and for our use case it's working quite well.

**Comment by Kyleeeez** [comment]
Thanks both, @coffeverton and @Tawpie .
Lucky I'm not playing custom sounds or having custom trigger events, I only use the `every` function but in the simplest way possible.
Any other thoughts?

**Comment by sta55en** [comment]
No.
No.
No.

You will tear out your hair and hate your life. Weird bad versioning, endless trouble trying to get builds working... take out this plugin and instantly everything works great. Stay far away.
