### ISSUE TITLE
Schedule New Notification Every Hour

### ISSUE THREAD

**Issue by onkar0777** [katzer/cordova-plugin-local-notifications#1721]
We are trying to develop an app which will show local notification according to users preference. The local notification should have a new text every time. The text will be saved locally. We need the app to work completely offline

## Your Environment

* Plugin version:0.9.0-beta.2
* Platform:Android
* OS version:
* Device manufacturer / model:
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): android 6.4.0
* Plugin config
* Ionic Version (if using Ionic) 3

## Expected Behavior

I want to schedule a different notification every hour. The notification data will be picked from local storage. Is this possible ?

## Actual Behavior

Not sure if this is possible.

## Context

We are trying to develop an app which will show local notification according to users preference. The local notification should have a new thought every time, hence the requirement. The thoughts will all be saved locally. We need the app to work completely offline

**Comment by koodroa** [comment]
Could you solve your problem? I'm trying to do the same but I can not schedule notifications at any time.

**Comment by Tawpie** [comment]
@onkar0777 The short answer is: Yes. As always, there are caveats:

0) use beta.3 with the fix from issue #1541 (I think that's the issue number, it corrects an android problem where notifications won't fire after the device has been rebooted)

1) you will have to schedule all of the notifications at the same time because it is not easy for an app to schedule notifications when it's not in the foreground. It may not be possible. I'm thinking you might be able to reschedule notifications when the onTrigger event runs, but thus far I've only seen onTrigger happen on Android, and there are more than a few people that haven't been able to get onTrigger to work on any platform.

2) iOS will not allow you to schedule more than 64 notifications at a time—it won't complain if you try to schedule more than 64, but it won't schedule more than 64. This means you'll need your user to launch your app at least every 64 hours else you will run out of notifications. Obviously, your app will need to reschedule the next 64 every time it launches.

**Comment by onkar0777** [comment]
@Tawpie thanks for your comment. We are going with the same approach.

But the point of the issue was to know if there was a method in the plugin to do it without having to loop over the notifications data. Like we provide an array with notification data and a frequency and then it automatically does the rest. It seemed a very generic requirement and hence I thought that it maybe a part of the plugin. But I guess looping and scheduling the notifs works fine, so no need of the feature.
