### ISSUE TITLE
Android7.0 or higher notification failed

### ISSUE THREAD

**Issue by zwdgit** [katzer/cordova-plugin-local-notifications#1732]
6 and below is OK，but 7.0 or higher Notification bar no response

**Comment by zwdgit** [comment]
cordova.plugins.notification.local.requestPermission always false，no selection box

**Comment by Steffaan** [comment]
Get the working code from [here](https://github.com/Steffaan/cordova-plugin-local-notifications)

**Comment by zwdgit** [comment]
Code is written in accordance with the document, but in Android 7.0 can not pop-up notification permission access window, users need to set the interface manually.

**Comment by mkn20** [comment]
Thanks. Seems to work on Pixel with latest Android Pie security update 5. But somehow not on Pixel3 with latest Android Pie security update 5. Any ideas? Both Android Pie security update seem to have different build numbers and not sure that makes any difference.

**Comment by zwdgit** [comment]
cordova.plugins.notification.local.requestPermission(function (granted) { ... });
Can this line of code get permission in Android 7.0? I've tried, but I can't. The demo provided by the government can't. Users need to open the application notification privileges manually in the settings.

**Comment by chadanuk** [comment]
@Steffaan  We have encountered this issue as well on Android > 7 (the notifications work but only partially) and using your fork seems to get it working as expected.

Is it worth submitting your fork as a PR since, currently, this package is the recommended package for ionic apps (https://ionicframework.com/docs/native/local-notifications/). So it would be great to have this resolved in this repo if possible?

**Comment by Steffaan** [comment]
@chadanuk I actually forked the project because PR's aren't getting merged here and the code isn't updated anymore. But not complaining here, the only reason the fork exists is because of all the work katzer put in.

Glad to hear the fork is working for you.

**Comment by GitToTheHub** [comment]
@Steffaan 
Hi Stefan, thanks you put work in this Plugin! Really great, you fixed some of the Android-Bugs. I will give it a try :)

**Comment by lovelyelfpop** [comment]
@zwdgit goverment.....chinglish 666

**Comment by andersborgabiro** [comment]
> Yes it should, let me know if it doesn't work.

@Steffaan 

I noted an oddity on Android 7: When I click on the notification text so that my app is shown, the notification doesn't disappear. There's neither any "remove all notifications" so it seems Android sees a notification with default settings as "permanent". I noticed that autoClear is true by default and priority is 0, and I don't change those. Neither do I set an explicit channel (for now), only an id, so I rely on a default channel being created.

This is all I do at the moment:

        cordova.plugins.notification.local.schedule(
                {
                    id: NOTIFICATIONID,
                    text: message,
                    badge: badge
                }
        );

Secondly, any word on the Cordova team making a core plugin for local notifications?

Thanks in advance,
Anders

**Comment by andersborgabiro** [comment]
This makes it non-sticky:

        cordova.plugins.notification.local.schedule(
                {
                    channel: "Primary",
                    id: NOTIFICATIONID,
                    text: message,
                    badge: badge,
                    autoClear: true,
                    sticky: false
                }
        );

**Comment by tverilytt** [comment]
@Steffaan Wow, kudos for great stuff, suddenly local notifications started to work again on Android Oreo :-)

**Comment by liuboren0617** [comment]
I had the same problem with android 9,  Has your entity been resolved?  @zwdgit
