### ISSUE TITLE
Question: When is the next release coming? Last update was on 13 Feb 2018 ?

### ISSUE THREAD

**Issue by CreativeArtDesign** [katzer/cordova-plugin-local-notifications#1763]
Or is this plugin going to the grave?

**Comment by sta55en** [comment]
Yup. Pretty much already in the grave. Doesn't seem to work with iOS12 after hours of trying to figure out what's going wrong.

**Comment by Tawpie** [comment]
I can't speak for the maintainer on whether or not it's a dead plugin walking, but "it works for me". Even on iOS 12.2 and Android 9.1. That said, I don't use the advanced functions, I just schedule to fire on a specific date+time because I don't need more than that. So far the alternative plugins are: :crickets:. I _think_ I asked the Cordova project to do a core plugin for notifications some time ago, to me notifications are a core functionality of a smartphone/tablet. If it's in the Cordova project, like it! If not, put in an issue... we'll all be happier.

**Comment by samuelfaj** [comment]
> I can't speak for the maintainer on whether or not it's a dead plugin walking, but "it works for me". Even on iOS 12.2 and Android 9.1. That said, I don't use the advanced functions, I just schedule to fire on a specific date+time (`at:`) because I don't need more than that. So far the alternative plugins are: :crickets:. I _think_ I asked the Cordova project to do a core plugin for notifications some time ago, to me notifications are a basic functionality of a smartphone/tablet. If it's in the Cordova project, like it! If not, put in an issue... we'll all be happier.

`at:` don't work for me (Android 8 and 9)... I've already opened a issue....
