### ISSUE TITLE
foreground : true, is Not Working

### ISSUE THREAD

**Issue by hanoj-budime** [katzer/cordova-plugin-local-notifications#1855]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version:` 0.9.0-beta.2`
* Platform: `android`
* OS version: `Windows 10`
* Device manufacturer / model: `Mi A1`
* Cordova version (```cordova -v```): `9.0.0 (cordova-lib@9.0.1)`
* Cordova platform version (```cordova platform ls```): `android 8.1.0`
* Plugin config
* Ionic Version (if using Ionic) :
```
Ionic CLI                     : 5.4.5 
Ionic Framework        : @ionic/angular 4.11.3
```

## Expected Behavior
 ```
this.localNotifications.schedule({
          foreground : true,
          sound: this.platform.is("android") ? 'file://sound.mp3': 'file://beep.caf',
          id: 2,
          text: `your back`,
          data: { secret: 'secret' },
          priority: 1
        });
```

_Tell us what should happen_

> Just add foreground:true in notification trigger call, and your notification will show up in the foreground, just like Whatsapp ! 

## Actual Behavior
 ```
this.localNotifications.schedule({
          foreground : true,  //not working 
          sound: this.platform.is("android") ? 'file://sound.mp3': 'file://beep.caf',
          id: 2,
          text: `your back`,
          data: { secret: 'secret' },
          priority: 1
        });
```
_Tell us what happens instead_

> foreground:true in notification not working

**Comment by HanojHanu** [comment]
please some one help me...!

**Comment by gwynjudd** [comment]
Probably related to the fix in this PR

https://github.com/katzer/cordova-plugin-local-notifications/pull/1696

**Comment by Arieru** [comment]
I have the same issue.

**Comment by Arieru** [comment]
> Probably related to the fix in this PR
> 
> #1696

How do I apply this fix in Ionic 4?

**Comment by HanojHanu** [comment]
> Probably related to the fix in this PR
> 
> #1696

PR means ?

**Comment by Arieru** [comment]
> PR means ?

Pull Request

**Comment by HanojHanu** [comment]
can any one help ?

**Comment by gwynjudd** [comment]
@HanojHanu if you are seeing a problem with android 8 or above, it is because of the change to do with channels (https://developer.android.com/guide/topics/ui/notifiers/notifications#ManageChannels). The plugin has got some support for channels, but the default channel it uses is not configured to use heads up notifications.

Possible solutions:

1. train your users to configure the default channel to display the notifications heads up
2. use the PR #1696 - with this PR, you can configure the channel at the time you create the notification for things like sound, heads up behaviour (pop on screen) and so on
3. create a channel yourself which is configured to use heads up behaviour, and use the name of that channel as the "channel" property in the options when you schedule the notification

I don't know which solution above is going to work for you
