### ISSUE TITLE
android forgets added local notifications after reboot

### ISSUE THREAD

**Issue by crapaam** [katzer/cordova-plugin-local-notifications#358]
Hi everybody!

I added the plugin with CLI, tested adding a notification and works great.
The only problem is that if I reboot de phone, android forgets all my notifications.
What am I doing wrong?
thanks in advance

Ale

**Comment by BassamTarek** [comment]
I'm experencing the same problem but i have noticed something that might be beneficial for someone in his analysis to the problem

I added this snippet of code in the initial view of my app so that i can check the scheduled Ids that are added as a local notification:

document.addEventListener('deviceready', function () {
	    // window.plugin.notification.local is now available
	    window.plugin.notification.local.getScheduledIds( function (scheduledIds) {
		    alert('Scheduled IDs: ' + scheduledIds.join(' ,'));
		});
	}, false);

and i get it work normally before the reboot and displays the id that i added, But after the reboot i noticed that:

1- If i opened the application in the first 3-5 seconds from the reboot: i see the same number added normally as it should be

2- After about 5 seconds i found that the local notification is removed.

So my conclusion is that the Public Class Restore is working normally but i guess that there is something that is removing the local notification after sometime

I hope that this can help in tracing the problem
Best Regards

**Comment by katzer** [comment]
The new 0.8.x release is a complete rewrite. If the issue still exists please reopen it.

You may also take a look into the new [wiki](https://github.com/katzer/cordova-plugin-local-notifications/wiki).

Thanks!

**Comment by Divyaadz** [comment]
Same issue, after phone rebooted daily scheduled notification is not displaying
