### ISSUE TITLE
0.7.8 on PhoneGap Build ?

### ISSUE THREAD

**Issue by ccloquet** [katzer/cordova-plugin-local-notifications#411]
Dear contributors to the Local Notifications plugin, 

Tanks for this very nice and practical plugin ! I noticed that the version on PGB is still 0.7.5. It would be great if the 0.7.8 version would also be available. Is this planned ?

Thanks again and best regards,

**Comment by neil-rowe** [comment]
you can fork the 7.8 and pull it in as a private plugin to use in your phone gap build project, but i haven't gotten it to function with IOS 8.1.3 yet .. working on it

**Comment by katzer** [comment]
@ccloquet,

yes its planned earlier this month. Since PGB requires a payed account to submit plugins it has not been submitted immediately.

**Comment by ccloquet** [comment]
Thanks !

**Comment by neil-rowe** [comment]
..also why not just use 8.0? it works great, and you can also just fork it and just give it its own id(because build only takes 1 plugin for any given plugin id) in the plugin.xml and you can use it as a private plugin in phonegap build.   it will package and build with your app and theres no extra work to do besides giving it a unique id .. just add something unique to the end of the current id.

**Comment by katzer** [comment]
v0.7.8 and v0.8.0 are both available on PGB now
