### ISSUE TITLE
Click event when app is running

### ISSUE THREAD

**Issue by stefanmdt** [katzer/cordova-plugin-local-notifications#435]
[This part of the documentation](https://github.com/katzer/cordova-plugin-local-notifications/wiki/04.-Scheduling) says, that the click event "will also get fired after launch when the app was not running". In my case it gets ONLY fired, when app was not running.

So, is the bug in the docs or in my app? :)

Thx in advance. BTW: really great plugins ...

**Comment by katzer** [comment]
The click event gets fired in both cases. You can try out the Kitchen Sink App from the sample branch.

Thank you. If you like you can support the plugin [here](https://github.com/katzer/cordova-plugin-local-notifications/wiki#how-can-i-support-you).

**Comment by stefanmdt** [comment]
Thanks for your reply. I've already installed the sample app and if I schedule a 5 sec notification and close the app, I see a toast saying "clicked 1" and if app is not closed then "triggered 1" ... exactly like in my case ...

**Comment by katzer** [comment]
Android or iOS?

**Comment by stefanmdt** [comment]
iOS 8.1.3 ... how should it look like? triggered and clicked visible at the same time?

**Comment by katzer** [comment]
OK, `click` means that the user has clicked on the notification. If you go to the notification center and click on the notification, the app will open or come to foreground and you will see a toast saying "clicked x".

`trigger` means that the event has occurred and the notification was added to the notification center. You receive that event in foreground, but usually not in background. Because in background you app is sleeping and the event get lost. Would you use the background-mode plugin in combination, then you would also receive the _triggered_ event in background.

Makes sense?

**Comment by stefanmdt** [comment]
Okay, I should have been more precise: In the second case, I schedule a 5 sec notification, push the home button to hide the app, click on the notification, app comes to foreground and says "triggered" but not "clicked".

**Comment by katzer** [comment]
How fast do you click on the notification? Hope not faster than one second. Because iOS does not say if its a click or trigger event. Thats why the plugin fires the click event if the trigger time is more than a second in the past and otherwise it fires the click event.

**Comment by stefanmdt** [comment]
Yeah, faster. :) That was the problem.
