### ISSUE TITLE
autoCancel options not working

### ISSUE THREAD

**Issue by shlomisas** [katzer/cordova-plugin-local-notifications#439]
looks like the Android native hard-coded set the value to true even if i made it to false on the JavaScript code.

File: platforms\android\src\de\appplant\cordova\plugin\notification\Builder.java
Line: 133

**Comment by katzer** [comment]
@shlomisas, the `autoCancel` property has been removed because cross-platform support isn't possible anymore. But if you need persistent notifications on Android, you can use the `ongoing` flag.

For more informations see [here](https://github.com/katzer/cordova-plugin-local-notifications/wiki/Upgrade-Guide).

**Comment by shlomisas** [comment]
@katzer, as far as i saw on my device (Galaxy S4) the ongoing flag is good just to not allow the user slide-off the notification but to remain the notification sticky even after the user click on it it's just the AutoCancel flag does.

**Comment by katzer** [comment]
@shlomisas, the current build does include a android specific autoCancel flag as it was in 0.7
