### ISSUE TITLE
Unregister permissions

### ISSUE THREAD

**Issue by MisterJack49** [katzer/cordova-plugin-local-notifications#537]
Is there a way to unregister from local notification, when the user want to disable it ?

**Comment by Vacietis** [comment]
Yes, same here! Please some response??

**Comment by MisterJack49** [comment]
Hi there ?

**Comment by mix3d** [comment]
You can cancel any pending notifications using the methods here.

https://github.com/katzer/cordova-plugin-local-notifications/wiki/07.-Cancelation

just use the `cancelall` event. You will have to build this into your app.

Otherwise, a user can disable notifications for your app in their device's respective settings areas. (iOS and Android both can do it, but the settings are different)

**Comment by katzer** [comment]
It's not possible to change the permissions in direct way. The user has to go to settings to change them.
