### ISSUE TITLE
Local notification  not working on Exact day and time. 

### ISSUE THREAD

**Issue by Ketan108ideaspace** [katzer/cordova-plugin-local-notifications#548]
Below code is properly works.

var now = new Date().getTime(),
_5_sec_from_now = new Date(now + 5 * 1000);
var sound = device.platform == 'Android' ? 'file://sound.mp3' : 'file://beep.caf';
cordova.plugins.notification.local.schedule({
                    id: 1,
                    title: 'Scheduled with delay',
                    text: 'Test Message 1',
                    at: _5_sec_from_now,
                    sound: sound,
                    badge: 12
});

I have used your plugin according example below is my code.
 
cordova.plugins.notification.local.schedule({
        id: 1,
        title: "Production Jour fixe",
        text: "Duration 1h",
        firstAt: monday_3_55_pm,
        every: "week",
        sound: "file://sounds/reminder.mp3",
        icon: "http://icons.com/?cal_id=1",
        data: { meetingId:"123#fg8" }
    });

Above code is not working.

**Comment by tomzx** [comment]
@Ketan108ideaspace, I believe this is because of how the schedule is setup.

For repeating events, in [Notification.java](https://github.com/katzer/cordova-plugin-local-notifications/blob/master/src/android/notification/Notification.java#L177), the "start" time used to determine period is `triggerTime`.

```
long triggerTime = options.getTriggerTime();
```

In [Options.java](https://github.com/katzer/cordova-plugin-local-notifications/blob/master/src/android/notification/Options.java#L215), you can see that `getTriggerTime()` return the following:

```
        return Math.max(
                System.currentTimeMillis(),
                options.optLong("at", 0) * 1000
        );
```

And thus, for it to have the behavior you want it to have, the "at" option must be a value in the future,  otherwise it will take the current timestamp and use it as your initial "at", which is generally not what you want.

Now, I'm unsure why this decision was made. To me, it makes sense to say that if I want it to start at 8AM today and have a period of 24h, but it is now 9PM, then it should only trigger tomorrow at 8AM, not trigger now at 9PM and trigger tomorrow again at 9PM.

**Comment by katzer** [comment]
On Android the exact time is not guaranteed.

> To me, it makes sense to say that if I want it to start at 8AM today and have a period of 24h, then it should trigger tomorrow morning at 8AM.

```javascript
schedule({
    firstAt: tomorrow_at_8,
    every: "day"
})
