### ISSUE TITLE
Notifications when app in foreground for android

### ISSUE THREAD

**Issue by djangojack** [katzer/cordova-plugin-local-notifications#625]
I know that local notifications are not supposed to work when the app is in the foreground, but this isn't the case for android. 

android -> Local Notifications when app in **foreground** / background / closed completely
ios -> Local Notifications when app in background / closed completely.

Is this normal?

**Comment by mix3d** [comment]
That is the expected behavior for each platform, yes. 

In iOS, the notifications will fire, and if you open the notifications tab, you will see that they are there. However, Apple's design people decided that if you are already in the app, you shouldn't see a notification, even when it fires. 

Many native local-notification tutorials will have a hook that will launch an in-app alert when the notification fires while the app is open, to get around this design "bug".

**Comment by sallem** [comment]
In the follwing page : https://github.com/katzer/cordova-plugin-local-notifications/wiki/04.-Scheduling

*The essential purpose of local notifications is to enable an application to inform its users that it has something for them — for example, a message or an upcoming appointment — **when the application isn’t running in the foreground**.*

But on android, the notification fires  even in foreground ... If this behavior is correct for Android devices, what could we do to allow notification launch only in background state ?

**Comment by ymc-sise** [comment]
Is there an answer for this question: 
But on android, the notification fires even in foreground ... If this behavior is correct for Android devices, what could we do to allow notification launch only in background state ?

**Comment by dave-mcclurg** [comment]
I think the answer is periodic updates while the app is running. When the app is running, you can periodically update the local notifications such that if any is just about to fire, you delete it.  That way, you never get a local notification while the app is running.  But if the app is dismissed, all the local notifications are scheduled.

**Comment by katzer** [comment]
Foreground notifications will come in future versions.
