### ISSUE TITLE
Question: Is this project still alive?

### ISSUE THREAD

**Issue by Krysisx** [katzer/cordova-plugin-local-notifications#629]
Is @katzer still working on this project or has it been abandoned?

Thanks

**Comment by mix3d** [comment]
Based on how much is posted to the issues page, probably not, but there have been a few relatively insignificant updates in the last few months; who knows.

 There are enough fixes for the biggest problems, however, so by reading through the right threads you can get it working to your needs. Shame, since this is really the only notification plugin.

**Comment by Krysisx** [comment]
yes exactly, I really need this plugin for my work so I really hope the developer has not abandoned it.

**Comment by slikk66** [comment]
I've been stuck with the linker error for days now, unable to find a working fix for iOS - about to remove from project completely... shame

**Comment by Tawpie** [comment]
perhaps a euro or two might help?

**Comment by katzer** [comment]
@Tawpie :+1: :+1: 

@Krysisx, @mix3d, @slikk66 
I am working full-time, I am having a company, employees and customers to manage, a family and beside I am maintaining (!) open source software. Let me know if you have ideas for improvements. I am open to it.
