### ISSUE TITLE
swap registerPermission for hasPermission in schedule() to support multiple schedule() calls

### ISSUE THREAD

**Issue by Chris--S** [katzer/cordova-plugin-local-notifications#634]
As far as I can tell the problem with making several calls to schedule() in the same js thread, is that the new notification is set via a callback in registerPermission and iOS only executes one (the last) of several queued calls to that function.

I realise that it is nice that the app author doesn't have to pay any particular attention to register permissions but the downside of having to group all disparate notifications together before making one call seems worse.

Possibly, using some doOnce flag to call registerPermission with the first schedule and hasPermission for any others would work.

**Comment by Chris--S** [comment]
Also, does hasPermission() implementation need to be in background?

Couldn't a permission lookup been done quickly and directly in the same thread?

**Comment by mix3d** [comment]
I havent looked into how it is implemented, but the documentation says to schedule all notifications at the same time, via an array. 

In my own experience, I'm setting two different notifications individually, via user-input events, and they both fire, so perhaps the issue is that you are setting multiple notifications with the same notification ID?

**Comment by Chris--S** [comment]
No, I'm using two different IDs.

Yes, the documentation says to schedule multiple notifications in an array, for the reason you have to do that see my explanation in the first para above.

If you set two notifications individually, via user input events, they aren't being set in the same thread.  One user input event will trigger its callback, make its notification request, exit and release.  The notification callback will fire almost immediately.  Then the next user input event will fire.  You can follow all this happening using the debugger in Safari with some strategically placed console logging.

**Comment by katzer** [comment]
@Chris--S If you are trying to schedule multiple ones at same time, you have to put them into an array. Theres also no need to call `registerPermission` or `hasPermission` since `schedule` is doing that for you.

Since the issue is from Jul/Aug please reopen the ticket if its still a topic with latest version.

**Comment by Chris--S** [comment]
@katzer - It was still an issue at Oct 9 version.  

I'm suggesting the problem of being forced to schedule multiple notifications using an array is resolvable by having ```schedule``` use ```hasPermission``` rather than ```registerPermission```.  I've made that change and have not noticed any side-effects (apart from ensuring ```registerPermission``` is called before I schedule any notifications).

**Comment by katzer** [comment]
@Chris--S you can make use of the new `skipPermission` flag.

```js
schedule(notifications, callback, scope, { skipPermission:true });
```

Additionally `registerPermission` delegates to `hasPermission` after first usage.
