### ISSUE TITLE
Not scheduling local-notification while app in background on ios8

### ISSUE THREAD

**Issue by hgo** [katzer/cordova-plugin-local-notifications#644]
While app is in background a websocket message being received however local notification is not shown until app goes to foreground on iOS 8

**Comment by WassiMan** [comment]
Any news on that issue?

**Comment by FlossyWeb** [comment]
+1 Same here

**Comment by jfaigan** [comment]
+1 Same issue for me on iOS 9.  Any movement on this issue?

**Comment by katzer** [comment]
@hgo Thats the nature of the iOS app life cycle - Paused in background

**Comment by loolooii** [comment]
According to [this](http://stackoverflow.com/questions/25356064/getting-local-notification-while-the-app-is-in-background) and [this](http://stackoverflow.com/questions/16811466/local-notification-in-background), you should be able to receive the notification even if the app is in background, but you cannot get a callback about whether or not you actually received the notification. Am I wrong? Because this sounds really weird, why would you not be able to receive local notifications when the app is in background? @katzer
