### ISSUE TITLE
Not compatible with Phonegap Build

### ISSUE THREAD

**Issue by gravitymediallc** [katzer/cordova-plugin-local-notifications#692]
This plugin doesn't appear to be compatible with Adobe Phonegap Build anymore.
![screen shot 2015-09-29 at 10 42 57 am](https://cloud.githubusercontent.com/assets/14287242/10167525/e1614cbe-6696-11e5-813a-55456e6e500b.png)

**Comment by alias** [comment]
It happens since PG switched to cli-5.2.Nailing to 3.7.0. all is fine.

To be more specific, this is the error in the phonegap provided logs (no matter if the plugin is fetched from npm or pgb):
<snip>
:processDebugResourcesWarning: AndroidManifest.xml already defines debuggable (in http://schemas.android.com/apk/res/android); using existing value in manifest.

:generateDebugSources
:compileDebugJava/project/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:564: error: cannot find symbol
                    webView.evaluateJavascript(js, null);
                           ^
  symbol:   method evaluateJavascript(String,<null>)
  location: variable webView of type CordovaWebView
/project/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:561: error: cannot find symbol
        webView.post(new Runnable(){
               ^
  symbol:   method post(<anonymous Runnable>)
  location: variable webView of type CordovaWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
</snip>

**Comment by katzer** [comment]
Has been fixed
