### ISSUE TITLE
Local Notification build fails

### ISSUE THREAD

**Issue by murliatdure** [katzer/cordova-plugin-local-notifications#712]
Unable to build the project with the following configurations:
Android API : 22
Cordova CLI : 5.3.3

![image](https://cloud.githubusercontent.com/assets/7137859/10482844/314d33ba-7299-11e5-93bb-204b0af691e1.png)

![image](https://cloud.githubusercontent.com/assets/7137859/10482863/4d350896-7299-11e5-901f-0832ba676031.png)

**Comment by insane210** [comment]
The same happens to me also.

**Comment by coddypotter** [comment]
following

**Comment by JcDenton86** [comment]
android-support-v4.jar already exists on new cordova because minsdk now is API 14. If you try to install android-support-v4 plugin on cordove 5.4.0 version you get this error:
> Failed to install 'cordova-plugin-android-support-v4':Error: Uh oh!
> "/Users/user/Desktop/project/platforms/android/libs/android-support-v4.jar" already exists!

I was using this plugin for earlier versions of cordova and is fine but now it needs to update with the new cordova tools etc because the same error appears again and cannot build the project.

Any suggestions or updates would be helpful

**Comment by katzer** [comment]
Should not be a problem anymore
