### ISSUE TITLE
Can I use the plugin on IOS 9

### ISSUE THREAD

**Issue by zhujunwei** [katzer/cordova-plugin-local-notifications#715]
it will be terminated on IOS 9.0 when i want to push the local notifications.

**Comment by Linerd00** [comment]
I am using version 0.8.1, the crash issue on IOS9 can be fixed by:

**Comment by Linerd00** [comment]
I am using version 0.8.1, the crash issue on IOS9 can be fixed by:
Replace: @property(readwrite, assign) NSDictionary* dict;
with: @property(nonatomic, retain) NSDictionary* dict;
in file APPLocalNotificationOptions.m

but I encounter another issue that scheduled notification being fired or received twice, still debugging.

**Comment by arhided** [comment]
Thank You so much my Friend! Fix works.

**Comment by katzer** [comment]
iOS9 is supported with 0.8.2
