### ISSUE TITLE
Visual studio error plugin

### ISSUE THREAD

**Issue by ZetDeveloper** [katzer/cordova-plugin-local-notifications#783]
I can not add the plugin through visual studio

**Comment by galebnas** [comment]
Same problem here 
"visual studio was unable to parse plugin.xml"

**Comment by katzer** [comment]
@ZetDeveloper Visual studio is out of scope for me. The plugin.xml is valid. Do you have some more informations what shall be invalid in detail?

**Comment by thealchemistbr** [comment]
Hi,

I was having the same problem, in case, it was because of this line:
```
<engine name="cordova-ios" version="<4.0.0" />
```
This < signal keeps crashing. I downloaded the zip, removed this, added locally and it worked fine - may not help you in case you're trying something with iOS, but for me (Android only), it worked like a charm.

Hope this helps,

Marcelo

**Comment by katzer** [comment]
I tried out with VS 2015 and newest version of cordova CLI and cordova windows platform without any problems.

I am wondering why only the last line shall be an issue but at least I am hoping to remove the iOS constrain soon.

```xml
<engines>
    <engine name="cordova" version=">=3.6.0" />
    <engine name="cordova-plugman" version=">=4.3.0" />
    <engine name="cordova-ios" version="<4.0.0" />
</engines>
``

**Comment by katzer** [comment]
@ZetDeveloper, @thealchemistbr I have removed the line, see 9dd5e06.
