### ISSUE TITLE
Android: Change LED color, flashing rate

### ISSUE THREAD

**Issue by Cosmack** [katzer/cordova-plugin-local-notifications#816]
Is there a way to do this with this plug-in? Sorry if this is the wrong place to ask. Just curious.

I think in Android the properties are called ledARGB, ledOffMS & ledOnMS.

**Comment by Cosmack** [comment]
Nevermind, found it.

**Comment by djangojack** [comment]
@Cosmack What did you find? My LED is flashing very quickly, and I would like to change this.

**Comment by Tawpie** [comment]
Me too! @Cosmac please let us in on the secret... led: 0x??????. I'm not happy with the frantic red, it looks like the phone is in deep deep trouble. A decoder ring would be handy to have in the wiki.

**Comment by Tawpie** [comment]
The decoder ring: the "led:" string consists of three hex bytes, each indicating the brightness of the red, green and blue LEDs in that order. Thus "FF0000" is red fully on, green fully off, blue fully off. "00FF00" is green (because red and blue are off), and "0000FF" is blue. The android documentation allows a fourth most significant byte to indicate the 'alpha', this is set to FF inside of the plugin.
