### ISSUE TITLE
collisions with push plugin and badge plugin

### ISSUE THREAD

**Issue by hagaisela** [katzer/cordova-plugin-local-notifications#822]
Hi,
I have an app which uses both push notifications and local notifications. I want the app's badge to be incremented by both of them.
I thought about implementing this using the cordova badge plugin, and using it's increment function when a push notification is received or when a local notification is triggered. I tried to add the badge plugin but got a duplicate symbol message when I linked the app.

duplicate symbol _UIApplicationRegisterUserNotificationSettings

**Comment by VPliss** [comment]
Hi,
Same problem with local-notification 0.8.4 and badge 0.7.1

duplicate symbol _UIApplicationRegisterUserNotificationSettings

**Comment by bayhall-digital** [comment]
I have conflict when using PGB and including via NPM - but I think boils down to similar issues?

**Comment by RegexLLC** [comment]
I'm having the same issue with iOS, a few people have had success hacking with previous versions, you can find them here in the old issues. I can't get the current local notifications / app events and push to work together either. They try to register at the same time if neither of them are.

**Comment by kvanniarajan** [comment]
In case someone wants to use the conflicting versions (as it was in my case), the approach should be to patch de.appplant.cordova.plugin.local-notification to use cordova-plugin-app-event instead of cordova-plugin-registerusernotificationsettings. 

Steps as follows:
in de.appplant.cordova.plugin.local-notification/plugin.xml, replace 
`<dependency id="cordova-plugin-registerusernotificationsettings" />` with
`<dependency id="cordova-plugin-app-event" />`

in de.appplant.cordova.plugin.local-notification/src/ios/APPLocalNotification.m, replace
`#import "AppDelegate+APPRegisterUserNotificationSettings.h"` with
`#import "AppDelegate+APPAppEvent.h"`

Then remove the old plugin (which should no more be a dependency):
`cordova plugin remove cordova-plugin-registerusernotificationsettings --save`

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by rwillett** [comment]
No update so closing
