### ISSUE TITLE
Can a data object get a notification's id number?

### ISSUE THREAD

**Issue by robochris** [katzer/cordova-plugin-local-notifications#831]
When i generate a notification the id number is random by using `Math.floor(Math.random() * 1000000000)`. I would use the MAX_VALUE but it doesn't seem to send a notification when i use that. Anyways if i had something like this:
`data: {
               eventId: 1523861,
               time: 24
            }`
Could i get that notification's Id using the `eventId`.
I'm trying to cancel a notification but i can't because i don't know the Id number.

Thanks for your help. I know i could got somewhere else like stackoverflow but i wanted to hear from someone that actually knows the code well.

**Comment by stormwin** [comment]
Try this:
Implement key/value map in your app.
Let 'key' be your eventid and 'value' be notificationId.
You need a counter for notificationId. Just increment it every time you want to create new notification and use it in schedule call. After call, do this: map[eventid] = counter;
When you want to update/cancel/clear existing notification just do map[eventid] and you will get notificationid. The other is same

Maybe this kind of technique should be implemented inside this plugin. Just an idea
I have already implemented it in my fork and it works great, but it is not egible for pull request because i have made lots of other modifications for my needs

**Comment by Zapmobilegames** [comment]
I would just add my experience in this matter. I use a guid generation function for all my objects and also for notifications id (numbers and chars), anyway I saw it was not suitable for notif id. It would be nice to have such key/value map as you suggested before, in next releases.
Thank you.
