### ISSUE TITLE
Not showing Notification after device reboot 

### ISSUE THREAD

**Issue by rashnk** [katzer/cordova-plugin-local-notifications#898]
i scheduled a notification at  10:20 am then turned off my device at 10:15am, i turned on at 10:22am , it didnt show that notification, is this way the android behaves by default, 
is there any way to show the un triggered notification when device on?

**Comment by dansanti** [comment]
i supposed because was on past, on device reboot,  is checked if alert is in past, if is TRUE, alert is not fired

**Comment by rashnk** [comment]
please be clear on your point

**Comment by dansanti** [comment]
when android start after reboot, he check all notifications, if notification was in past , i supposed shouldn't fired, because was in past.
In your example, notification was scheduled to 10:20 and you turn on your android at 10:22, then notifications is not fired because was in past... 

Look out this commit https://github.com/katzer/cordova-plugin-local-notifications/commit/0a44a11ac69125f782817accd14b0df4a006a7c2
isScheduled() checks if notifications was on past, if True, can't be rescheduled, and cancel notification

public boolean isScheduled () {
        return isRepeating() || !wasInThePast();
    }


then, at start this app, checks if notification was in past, and in your example, was in past so, this mean that not posible be fired.

**Comment by rashnk** [comment]
Thanks :+1:

**Comment by dansanti** [comment]
@rashnk please close this issue
