### ISSUE TITLE
trigger event not fired when app closed?

### ISSUE THREAD

**Issue by souly1** [katzer/cordova-plugin-local-notifications#899]
Hi, 
great plugin - well developed.

I had a question, not sure whether it's a bug or expected behaviour which is not planned to be changed: when the app is closed and not in memory the notification fires up just fine, but the "trigger" event and code is not triggered and is only fired when app is opened.
Perhaps to have code in event handler run in this situation this plugin should be used in conjunction with https://github.com/MobileChromeApps/cordova-plugin-background-app?
Thanks

**Comment by roysG** [comment]
Me to, any explain for that?

**Comment by Heshyo** [comment]
@souly1 I saw your comment https://github.com/wnyc/cordova-plugin-wakeuptimer/issues/13#issuecomment-195037425 So it means you were able to modify this plugin to make it start your app, instead of getting a notification and having to click it? If so you may want to send a pull request.

I found the following related issue https://github.com/katzer/cordova-plugin-local-notifications/issues/750

**Comment by souly1** [comment]
Hey @Heshyo , I planned to do just that, but it ended up working code, but very hard coded, only a solution for android and not thoroughly tested. I'll think about adding a pull request for reference of other users. Thanks

**Comment by pan100** [comment]
+1

**Comment by katzer** [comment]
In general its not possible. On Android it is, however launching the app "just by nothing" is very special use case. Maybe I will add such `launchOnTrigger` flag, not sure yet.

**Comment by StefanRein** [comment]
https://github.com/katzer/cordova-plugin-local-notifications/issues/1798#issuecomment-656962391
