### ISSUE TITLE
Periodic notifications not taking into account daylight savings

### ISSUE THREAD

**Issue by jorgecachoh** [katzer/cordova-plugin-local-notifications#922]
Hi,

It seems the plugin fails when you have a local notification scheduled on a periodic basis (daily, weekly, ...) and a daylight saving change happens.

Example: I have a local notification scheduled daily at 22:00 and it's working ok, but since last daylight saving change (move 1 hour forward) the notification is displayed at 23:00.

Android date is correct and it shows real time, but local notification is displayed at "wrong" time (not talking into account date change)

Thanks

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by rwillett** [comment]
No update from original poster so closing.

**Comment by souly1** [comment]
Still an issue, happened then and happening now again, just seeing the grades in app store plummet down on this issue...

**Comment by rwillett** [comment]
See #1241 for a solution.

**Comment by souly1** [comment]
Seen that, already using another Date library in my projects using this plugin, but I guess that I'll have no choice if you don't plan to solve this issue, to avoid the european change issues. Just thought you might want to solve this as part of the plugin as it needs to be so that people adding the plugin in the future won't discover it after bad reviews in app store.

**Comment by souly1** [comment]
Also, it's unclear if this will solve the issue for periodic notifications where the reminders were set a long time ago...

**Comment by rwillett** [comment]
I'm not the author of the plugin.
