### ISSUE TITLE
Local Notifications work fine in Android, don't work in iOS

### ISSUE THREAD

**Issue by jjrchrds** [katzer/cordova-plugin-local-notifications#924]
I'm using ionic 2.0.0-beta.22
notifications are fine in Android, but don't do anything in iOS

here is an example that is fine in Android, but does nothing in iOS

`setPmNotification($event){
        var pm_notification = new Date();
        // pm_notification.setHours(16, 0, 0, 0);

```
    if (window.cordova) {
        window.cordova.plugins.notification.local.schedule({
            id: 2,
            title: 'Good Evening!',
                    text: "It's time to take 2 puffs of Symbicort®",
            data: {
                customProperty: 'custom value'
            }
        }).then(function (result) {
            console.log('Notification 2 triggered');
        });
    }
}`
```

**Comment by andersborgabiro** [comment]
Same here. Might have been something that went bonkers after the latest iOS release a few days ago.

Not that I get this version of the plugin to work at all. I've previously used "-mm". With this plugin I get this in PhoneGap Build:

Build Date: 2016-04-04 11:23:22 -0700
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-plugin-whitelist" via npm
Installing "cordova-plugin-whitelist" at "1.2.1" for ios
Fetching plugin "cordova-plugin-device" via npm
Installing "cordova-plugin-device" at "1.1.1" for ios
Fetching plugin "cordova-plugin-inappbrowser" via npm
Installing "cordova-plugin-inappbrowser" at "1.3.0" for ios
Fetching plugin "cordova-plugin-dialogs" via npm
Installing "cordova-plugin-dialogs" at "1.2.0" for ios
Fetching plugin "cordova-plugin-appversion" via npm
Installing "cordova-plugin-appversion" at "1.0.0" for ios
Fetching plugin "cordova-plugin-x-toast" via npm
Installing "cordova-plugin-x-toast" at "2.5.0" for ios
Fetching plugin "cordova-plugin-network-information" via npm
Installing "cordova-plugin-network-information" at "1.2.0" for ios
Fetching plugin "cordova-plugin-globalization" via npm
Installing "cordova-plugin-globalization" at "1.0.3" for ios
Fetching plugin "cordova-plugin-vibration" via npm
Installing "cordova-plugin-vibration" at "2.1.0" for ios
"plugman install --platform ios --project /project --plugin cordova-plugin-local-notifications": Fetching plugin "cordova-plugin-local-notifications" via npm
Installing "de.appplant.cordova.plugin.local-notification" at "0.8.2dev" for ios
Notice: org.apache.cordova.device has been automatically converted to cordova-plugin-device and fetched from npm. This is due to our old plugins registry shutting down.
Dependent plugin "cordova-plugin-device" already installed on ios.
Fetching plugin "de.appplant.cordova.common.registerusernotificationsettings" via npm
Failed to install 'de.appplant.cordova.plugin.local-notification':CordovaError: Failed to fetch plugin de.appplant.cordova.common.registerusernotificationsettings via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/de.appplant.cordova.common.registerusernotificationsettings
    at /usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/fetch.js:146:33
    at _rejected (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
Failed to fetch plugin de.appplant.cordova.common.registerusernotificationsettings via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/de.appplant.cordova.common.registerusernotificationsettings

**Comment by pierreNeck** [comment]
same probleme

**Comment by andersborgabiro** [comment]
I use it the simplest way possible, without scheduling, only immediate. Not a sausage.

**Comment by jjrchrds** [comment]
Still no luck with ios. It looks like ionic 2 actually has an ionic-native plugin for local notifications. Might try that today.

Just to be clear, it works well with android. @andersborgabiro are you using the click event on the notification?

**Comment by andersborgabiro** [comment]
No, this is all I do. I'm suspicious about notificationPermission.

```function notificationPermission() {
    if (device.platform.toLowerCase() === "ios") {
        cordova.plugins.notification.local.registerPermission();
    }
}

function notificationAdd(message) {
    cordova.plugins.notification.local.schedule({id: 1, text: message});
}```

**Comment by andersborgabiro** [comment]
The only thing I need is an immediate notification and that the app is invoked when the notification is clicked. No event is needed to perform further tasks.

I noticed that when I exited/stopped the app, a notification showed up. Likewise, when I clicked the Home button, but just once.

The investigation continues.

**Comment by pierreNeck** [comment]
I maked a simply app, with a button for displaying the local notification, there is no error, but the notification isn't displayed. I have a succes response with blank data.

**Comment by andersborgabiro** [comment]
Were you asked to give permission to issue notifications?

**Comment by pierreNeck** [comment]
.run in platform.deviceReady

**Comment by jjrchrds** [comment]
@andersborgabiro I'm sure it has something to do with the app permission as well, since no dialog is presented. Hopefully dev gets back to us.

**Comment by andersborgabiro** [comment]
@katzer Could you please make an effort on this? This is a show-stopper.

Do you know of any pull request that's supposedly fixed this?

I'm also wondering why I can't use this plugin for PhoneGap Build (I have to use "-mm"). Supposedly PGB uses the normal Cordova release behind the curtain.

Regards,
Anders

**Comment by andersborgabiro** [comment]
I get the permission question with "-mm", but no notifications show up.

**Comment by jjrchrds** [comment]
This is working now.

**Comment by pierreNeck** [comment]
Have you made change ? How are you fixing this issue ?

**Comment by andersborgabiro** [comment]
Pity the plugin doesn't work for PhoneGap Build.

**Comment by ibnbd** [comment]
Same problem, was working weeks ago, now not working on iOS.

**Comment by BenWise77** [comment]
Yeah no luck here either, iOS 9.3.1, I get a notifications permission dialog the first time but nothing after that.
```
cordova.plugins.notification.local.schedule({
  id: 1
  ,text: "Notification"
});
```

**Comment by sKuD51** [comment]
For my app, I force user to register permission. On app start I call : 
`cordova.plugins.notification.local.registerPermission(function (granted) {
					});`

**Comment by Firzenizer** [comment]
I'm also having this issue. Notifications work perfectly on Android, but iOS won't notify.

Using Phonegap build with following versions:

**Comment by andersborgabiro** [comment]
Considering the amount of issue reports: No one's working on this plugin.

Try some of the derivatives instead. I use cordova-plugin-local-notifications-san, to avoid issues with Google Play Services. Before that I used "-mm".

**Comment by rwillett** [comment]
Is this still an issue?

**Comment by rwillett** [comment]
No update from original poster so closing.
