### ISSUE TITLE
registerPermission and hasPermission not working

### ISSUE THREAD

**Issue by reinos** [katzer/cordova-plugin-local-notifications#939]
it looks like both `registerPermission` and `hasPermission` is not working at all.

**Comment by Danbardo** [comment]
Works for me

**Comment by reinos** [comment]
I use the http://ngcordova.com/docs/plugins/localNotification/ and try the following code

```
$cordovaLocalNotification.hasPermission(function(result){
    alert('has permission');
}, function(){
    alert('No permission');
});
```

but it shows nothing.

A line before i have 

```
/schedule the notification
$cordovaLocalNotification.schedule({
    id: 1,
    title: 'J,
    text: '',
    firstAt: parseInt(startTime.format('x')),
    every: "day"
}).then(function (result) {
    callback(result);
});
```

And thats working though.

**Comment by Danbardo** [comment]
I'm using Cordova, running something like this onDeviceReady:

cordova.plugins.notification.local.hasPermission(
     function (granted) {
          if(granted){
               alert('granted');
          }else{
               alert('not granted');
          }
     }
);

**Comment by reinos** [comment]
does `alert('not granted');` also fire an alert, or just `alert('granted');`

Its now working, but only `alert('not granted');` is fired.

**Comment by Danbardo** [comment]
The variable granted is a Boolean, it's either true or false.
When it's true it means that the user has allowed push notifications for the app.
When it's false it means that the user has not allowed push notifications.

Because you are seeing 'not granted' it means you have not granted the application access to create push notifications.

It sounds like you're testing on iOS is that right? To provide access you need to go into settings, click notification, scroll to your app and enable them.

You would of been prompted the first time you installed the app and created a push notification. This plugin can force a prompt using:

			cordova.plugins.notification.local.registerPermission(function (gr) {
				if(!gr){
					alert('They didn't give permission');
				}else{
					alert('They gave permission');	
				}
This only works once, the user will only ever see a permission prompt once. If you delete and reinstall the application, you will be able to see the prompt again.

**Comment by blattmann** [comment]
I have the same issue with iOS 8.1.1 on an iPhone 5s.
On iOS 9.x (iPhone 6, iPhone 6s Plus) and Android all works fine.

My code:

        cordova.plugins.notification.local.registerPermission(function (granted) {
          console.log('Permission has been granted: ' + granted);  
          $cordovaLocalNotification.schedule({
            id: noteid,
            title: noTitle,
            text: noText,
            sound: 'file://audio/fx02.caf',
            at: instantly,
            data: {
              hint: 'bluetooth'
            }
          }).then(function (result) {
            console.log('Notification triggered - id: ', noid);
            return true;
          });
        });

Debugging info in Xcode:

        Permission has been granted: true
        Attempting to schedule a local notification <UIConcreteLocalNotification: 0x1701566e0>{fire date = Friday 27 May 2016 12 h 35 min 22 s Central European Summer Time, time zone = Europe/Madrid (CEST) offset 7200 (Daylight), repeat interval = NSCalendarUnitEra, repeat count = UILocalNotificationInfiniteRepeatCount, next fire date = (null), user info = {
            at = 1464345322;
            badge = 0;
            data = "{\"hint\":\"bluetooth\"}";
            id = 1273911086;
            sound = "file://audio/fx02.caf";
            text = "Click for here more information.";
            title = "Please activate Bluetooth.";
        }} with a sound but haven't received permission from the user to play sounds

**Comment by katzer** [comment]
Please use 0.9-beta - thanks
