### ISSUE TITLE
All scheduled notifications appear when restarting phone only on Android (App build using Ionic Framework)

### ISSUE THREAD

**Issue by MBenoli** [katzer/cordova-plugin-local-notifications#940]
Hello guys,

Here is my issue: Let's consider for example that I have a function that schedules a notification every week. So five weeks after having installed my app, I would have had 5 notifications that would have been displayed (one every week). Then, I restart my phone (for whatever reason) and all the notifications that had been displayed during those five weeks appear all in once. I don't understand how come that the previous scheduled notifications appear all in once when I restart my phone? (By the way, I cancel those notifications after they have been displayed). This problem only appears on ANDROID, the same app on IOS works perfectly. So, how come those notifications appear? It's like they are never completely cancelled? I tried several variants to avoid this problem but it doesn't want to go away. Any ideas?

Thanks a lot!

**Comment by simonwatt** [comment]
I'm getting the same issue. Did you ever find a way around it?

I'm using Android 4.4.4 (KitKat); any previously displayed notifications are showing again after restarting the device. This issue is making the plugin unusable for me and I have no workaround.

For example if I have 5 notifications displayed for the day (and have viewed or cleared them), if I restart the device I'll now get the 5 notifications again directly after restarting the device.

It's worth noting that I'm using the PhoneGap Build for building my App.

Thanks

**Comment by simonwatt** [comment]
Nevermind, I read issue #https://github.com/katzer/cordova-plugin-local-notifications/issues/641 then realized my phonegap build config was pointing to a fork (cordova-plugin-local-notifications-mm) that doesn't include that fix. When I tell PhoneGap build to use the correct plugin off npm it's working fine:
<gap:plugin name="de.appplant.cordova.plugin.local-notification" source="npm" />

**Comment by rwillett** [comment]
Is this still an issue? Its over six months old.

**Comment by rwillett** [comment]
No update from original poster so closing.
