### ISSUE TITLE
Local notification doesn't work when app is killed? (With iBeacon)

### ISSUE THREAD

**Issue by szanellato93** [katzer/cordova-plugin-local-notifications#956]
Hi to everyone, i'm trying to active local notification when app is closed. I used iBeacon plugin and it launch the app in background when i'm near a beacon.. but notification in that case don't work. If i launch the app and after go in background mode, notification work. Someone can resolve this problem?

**Comment by lumarega** [comment]
I have the same issue using iBeacons and Local notification, it seems like the notifications don't work unless you open the app first and then go on background mode. I also would like to know if there is a way to launch it when the app is closed.

**Comment by rwillett** [comment]
Is this still an issue? Its nearly a year old.

**Comment by rwillett** [comment]
Closed as no response from original poster.

**Comment by saty932** [comment]
When you close the app it's not giving any notifications.
Finally we are able to get notify when the app is killed but not using local notifications.If you try with local notification it will never works because if you close the app it's not going to execute beacon methods.

We have created one repo it's using two plugins now it's able to get the notifications when the app is killed in android.
repo link:-
saty932/cordova-plugin-beacon-monitoring-in-background-with-notifications-android
