### ISSUE TITLE
Working Demo of Notification in Cordova 6.1.1 with iOS

### ISSUE THREAD

**Issue by clarkycat** [katzer/cordova-plugin-local-notifications#974]
Hi, I can't get notifications to fire in iOS with Cordova 6.1.1. Could someone upload a basic demo that works?

I've tried adding the plugin to the default cordova project template created with `cordova create …` but no luck. The only other plugin I added was `cordova-plugin-console`.

**Comment by snowbreeze** [comment]
Same issue here

**Comment by funkjunky** [comment]
Same. Web has access to the cordova.plugins object, but not the 'phonegap development' ios app' console.

**Comment by ronyrun** [comment]
which version of Cordova make everything works ?

**Comment by snowbreeze** [comment]
Its working on cordova 6 and ios 4, i.e latest of everything

**Comment by BenWise77** [comment]
@snowbreeze thanks for confirming, can you upload a code demo? because for me the plugin installed into a blank cordova project template does NOT work with cordova 6.1.1, cordova-ios 4.1.1, ios 9.3.1, x-code 7.3.1.

**Comment by snowbreeze** [comment]
cordova.plugins.notification.local.schedule({
                            id: id,
                            at:first,
                            text: message,
                            title: heading,
                            every:every
                            
                });

For the first I used momentjs. For every I used 'day'

**Comment by ronyrun** [comment]
On my side I have Cordova 6.1.1 and platform ios 4.1.1.

```javascript
//icon and beep files in the www folder.

if(!!window.cordova) {
          cordova.plugins.notification.local.schedule({
              title: "New Message",
              message: "Hi, are you ready? We are waiting.",
              sound: "file://sounds/beep.caf",
              icon: "file://img/icon.png"
            });
        }
```

# ON IOS : 

The local notification plugin **does** : 
- display a notification in the notifications list

The local notification plugin **does not** : 
- vibration on notification
- Displaying an alert or banner
- Playing a sound

**Comment by rlantigua** [comment]
@ronyrun which version of ios are you running on? I am using cordova 6..1.1, cordova-ios 4.1.1 and ios 9.3.1 and the plugin is not triggering any notification

**Comment by ronyrun** [comment]
Hi, 
There are notifications when the app is on Background mode.
Try to add this plugin.

**Comment by BenWise77** [comment]
Thank @ronyrun, You are right, it does display a notification in the list, I didn't notice that!

So notifications **are** working, but the problem is that there's no alert/banner/vibe/sound? That is odd, I've given the app permission to show them. How could there be a list notification but not the rest.

**Comment by ronyrun** [comment]
Yes I have the same pb. with Vibe and Sound.

**Comment by Crashthatch** [comment]
I also have this problem with Cordova 6.1.1: It appears in the notifications list from the top, but there's no alert/banner/vibe/sound.

**Comment by Crashthatch** [comment]
Went back and tried Cordova v5.4.1 but had the same problem. On v4.3.1 I got a different error (maybe this plugin is not compatible with Cordova v4 any more?)

```Installing "de.appplant.cordova.plugin.local-notification" for ios
TypeError: Cannot read property 'indexOf' of undefined
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:232:44```

**Comment by Crashthatch** [comment]
After investigating for the best part of a day, it appears iOS doesn't show notification alerts while the app is in the foreground which is why my "Test notification" button didn't appear to do anything other than add a notification to the notification center. If I trigger a notification while my app is running in the background (screen off, or while on the home screen), it makes a noise, vibrates and shows up on the lock screen.

This isn't a plugin, or even a cordova issue. Even native apps have to handle this issue by doing something like creating a popup / something handled by their own UI while the app is in the foreground: 
http://stackoverflow.com/questions/14872088/get-push-notification-while-app-in-foreground-ios

iOS 10 has the UserNotificationCenterDelegate which apparently can give you more control over foreground notifications (I have not tested):
https://developer.apple.com/reference/usernotifications/unusernotificationcenterdelegate

**Comment by BenWise77** [comment]
@Crashthatch hey thanks a lot for posting your findings, I've not had time to test this yet but it sounds like you solved the mystery!

**Comment by loolooii** [comment]
@Crashthatch I don't receive any notifications when in background, that is not normal behaviour, is it? Did you do something else to get it working? Because it does not work for me.

**Comment by Crashthatch** [comment]
@loolooii Cordova apps can get woken on various events (in my case, when location changes). iOS wakes the app (still in the background), lets it process for 5-10 seconds then puts it back to sleep. I use this time to do a bit of processing and issue a notification. 

I believe that plugin allows you to stay awake in the background, but I am not using it (the store compliance warnings put me off).

**Comment by loolooii** [comment]
@Crashthatch I'm using the background geolocation plugin ([this](https://github.com/mauron85/cordova-plugin-background-geolocation)), so I guess our cases are a bit similar. Somehow I don't receive the notification when the app is closed (and with closed I don't mean removing from memory, but simply clicking on home screen). When the app is opened I receive the notification only in notification list (as expected, I understand). Do you know what may be the problem? 

Otherwise, for something very simple, I have to implement push notifications only to send location to server and calculate something and send push notification back. That seems like an overkill to me.

**Comment by rwillett** [comment]
This works with IOS 8, 9 and 10 and Cordova 6.1 and Xcode 7.3, 8.1 and 8.2 and 8.3
