### ISSUE TITLE
Please We Need buttons on the notifications

### ISSUE THREAD

**Issue by lelolenda** [katzer/cordova-plugin-local-notifications#995]
Will be very useful

**Comment by DavidBriglio** [comment]
I have implemented this feature and made a pull request for it: #1003
Check out my fork if you need it ASAP though: [https://github.com/DavidBriglio/cordova-plugin-local-notifications](url)

**Comment by BioPhoton** [comment]
Thanks a lot for this PR!!!! <3

Tested it out already, it works well. Exactly what i needed.

**Comment by BioPhoton** [comment]
In you examples you use path to icon. Is there a list of available icons? Or is it possible to add own icons? Thx.

**Comment by DavidBriglio** [comment]
As far as I know all of the default android drawable icons work. I have not tested it with custom icons though. I don't have a list ready, but I will find one when I can.

**Comment by BioPhoton** [comment]
Would be great!!

**Comment by DavidBriglio** [comment]
I have tested and confirmed working custom icons inserted into the "res" folder, using the (Google Material Icons)[https://design.google.com/icons/]. As for the default ones: it is actually not recommended to use them because the dependency could break with updates. If you still want to use the default ones, the list can be found (here)[https://android.googlesource.com/platform/frameworks/base/+/master/core/res/res/drawable/].

**Comment by BioPhoton** [comment]
Very good information!!! 

So you downloaded the icons as png and intert them directly under platforms/android/res. 

Is this PR also working on ios?

**Comment by DavidBriglio** [comment]
As with other icons, you insert them in their respective res/drawable-?dpi folders. If you are using the Material Icons, the downloaded zip contains the proper file structure. This PR is only for android.

**Comment by okan** [comment]
@DavidBriglio thanks a lot. That is what I exactly need! Great contribution 👍

**Comment by katzer** [comment]
Have been added - use 0.9-beta
